In [2]:
import pandas as pd
import numpy as np
from pathlib import Path
import openpyxl

In [ ]:
path = (r'Projects\Sports Performance Analytics\Section 2 - Moneyball and Beyond\Data\Game logs 1999-2003.xlsx')
path = path.replace("\\", "/")
path

'C:/Users/nickc/OneDrive/Documents/Projects/Sports Performance Analytics/Section 2 - Moneyball and Beyond/Data/Game logs 1999-2003.xlsx'

In [4]:
df = pd.read_excel(path, engine='openpyxl')

In [5]:
pd.set_option('display.max_columns', None)
df

,date,game_number,day,visitor,visitor_lg,visitor_game_number,home,home_lg,home_game_number,visitor_score,home_score,outs,daynight,completion,forfeit,protest,park,attendance,game_minutes,visitor_linescore,home_linescore,visitor_ab,visitor_h,visitor_2b,visitor_3b,visitor_hr,visitor_rbi,visitor_sh,visitor_sf,visitor_hbp,visitor_bb,visitor_ibb,visitor_so,visitor_sb,visitor_cs,visitor_gidp,visitor_ci,visitor_lob,visitor_pitchers_used,visitor_individual_er,visitor_team_er,visitor_wp,visitor_balks,visitor_putouts,visitor_assists,visitor_errors,visitor_passed_balls,visitor_double_plays,visitor_triple_plays,home_ab,home_h,home_2b,home_3b,home_hr,home_rbi,home_sh,home_sf,home_hbp,home_bb,home_ibb,home_so,home_sb,home_cs,home_gidp,home_ci,home_lob,home_pitchers_used,home_individual_er,home_team_er,home_wp,home_balks,home_putouts,home_assists,home_errors,home_passed_balls,home_double_plays,home_triple_plays,hp_ump_id,hp_ump_name,1b_ump_id,1b_ump_name,2b_ump_id,2b_ump_name,3b_ump_id,3b_ump_name,lf_ump_id,lf_ump_name,rf_ump_id,rf_ump_name,visitor_manager_id,visitor_manager_name,home_manager_id,home_manager_name,winning_pitcher_id,winning_pitcher_name,losing_pitcher_id,losing_pitcher_name,saving_pitcher_id,saving_pitcher_name,gwrbi_batter_id,gwrbi_batter_name,visitor_starting_pitcher_id,visitor_starting_pitcher_name,home_starting_pitcher_id,home_starting_pitcher_name,visitor_batter_1_id,visitor_batter_1_name,visitor_batter_1_pos,visitor_batter_2_id,visitor_batter_2_name,visitor_batter_2_pos,visitor_batter_3_id,visitor_batter_3_name,visitor_batter_3_pos,visitor_batter_4_id,visitor_batter_4_name,visitor_batter_4_pos,visitor_batter_5_id,visitor_batter_5_name,visitor_batter_5_pos,visitor_batter_6_id,visitor_batter_6_name,visitor_batter_6_pos,visitor_batter_7_id,visitor_batter_7_name,visitor_batter_7_pos,visitor_batter_8_id,visitor_batter_8_name,visitor_batter_8_pos,visitor_batter_9_id,visitor_batter_9_name,visitor_batter_9_pos,home_batter_1_id,home_batter_1_name,home_batter_1_pos,home_batter_2_id,home_batter_2_name,home_batter_2_pos,home_batter_3_id,home_batter_3_name,home_batter_3_pos,home_batter_4_id,home_batter_4_name,home_batter_4_pos,home_batter_5_id,home_batter_5_name,home_batter_5_pos,home_batter_6_id,home_batter_6_name,home_batter_6_pos,home_batter_7_id,home_batter_7_name,home_batter_7_pos,home_batter_8_id,home_batter_8_name,home_batter_8_pos,home_batter_9_id,home_batter_9_name,home_batter_9_pos,additional_info,acquisition
0,19990404,0,Sun,COL,NL,1,SDN,NL,1,8,2,54,N,NaN,NaN,NaN,MNT01,27104,190,150001001,100000100,42,18,1,0,1,8,1,0,0,2,0,6,2,0,1,0,10,4,2,2,0,0,27,9,0,0,1,0,32,6,1,0,0,2,0,0,0,6,0,8,1,0,1,0,9,5,8,8,0,0,27,10,0,0,2,0,ripps901,Steve Rippley,darlg901,Gary Darling,poncl901,Larry Poncino,mealj901,Jerry Meals,NaN,(none),NaN,(none),leylj801,Jim Leyland,bochb002,Bruce Bochy,kiled001,Darryl Kile,ashba002,Andy Ashby,NaN,(none),hamid001,Darryl Hamilton,kiled001,Darryl Kile,ashba002,Andy Ashby,hamid001,Darryl Hamilton,8,peren001,Neifi Perez,6,harrl001,Lenny Harris,9,bichd001,Dante Bichette,7,castv001,Vinny Castilla,5,heltt001,Todd Helton,3,lansm001,Mike Lansing,4,manwk001,Kirt Manwaring,2,kiled001,Darryl Kile,1,veraq001,Quilvio Veras,4,sandr002,Reggie Sanders,7,gwynt001,Tony Gwynn,9,joynw001,Wally Joyner,3,myerg001,Greg Myers,2,ariag001,George Arias,5,river002,Ruben Rivera,8,gomec001,Chris Gomez,6,ashba002,Andy Ashby,1,NaN,Y
1,19990405,0,Mon,TBA,AL,1,BAL,AL,1,7,10,51,D,NaN,NaN,NaN,BAL12,46733,225,101111002,00420004x,38,12,3,0,2,7,1,0,2,5,0,10,1,0,0,0,12,5,10,10,0,0,24,11,0,0,2,0,33,13,2,0,2,10,1,1,0,6,0,7,0,0,2,0,7,6,7,7,0,0,27,10,0,0,0,0,cobld901,Drew Coble,hendt901,Ted Hendry,mcclt901,Tim McClelland,cedeg901,Gary Cederstrom,NaN,(none),NaN,(none),rothl101,Larry Rothschild,millr801,Ray Miller,mussm001,Mike Mussina,alvaw001,Wilson Alvarez,timlm001,Mike Timlin,bellj002,Albert Belle,alvaw001,Wilson Alvarez,mussm001,Mike Mussina,winnr001,Randy Winn,8,martd002,Dave Martinez,9,cansj001,Jose Canseco,10,mcgrf001,Fred McGriff,3,flahj001,John Flaherty,2,boggw001,Wade Boggs,5,sorrp001,Paul Sorrento,7,cairm001,Miguel Cairo,4,stock001,Kevin Stocker,6,andeb001,Brady Anderson,8,bordm001,Mike Bordick,6,clarw001,Will Clark,3,bellj002,Albert Belle,9,conij001,Jeff Conine,10,ripkc001,Cal Ripken,5,surhb001,B.J. Surhoff,7,johnc002,Charles Johnson,2,reboj001,Jeff Reboulet,4,NaN,Y
2,19990405,0,Mon,BOS,AL,1,KCA,AL,1,5,3,54,D,NaN,NaN,NaN,KAN06,40257,171,2002001,200000100,36,13,3,1,1,5,0,0,1,4,0,2,1,0,4,0,9,3,2,2,0,0,27,6,1,0,1,0,32,6,2,0,1,3,1,0,0,2,0,12,3,0,1,0,5,4,5,5,0,0,27,16,0,0,4,0,garcr901,Rich Garcia,reilm901,Mike Reilly,johnm901,Mark Johnson,welkt901,Tim Welke,NaN,(none),NaN,(none),willj107,Jimy Williams,muset101,Tony Muser,martp001,Pedro Martinez,appik001,Kevin Appier,gordt001,Tom Gordon,stanm002,Mike Stanley,martp001,Pedro Martinez,appik001,Kevin Appier,offej001,Jose Offerman,10,lewid001,Darren Lewis,8,valej002,John Valentin,5,garcn001,Nomar Garciaparra,6,oleat001,Troy O'Leary,7,stanm002,Mike Stanley,3,hatts001,Scott Hatteberg,2,fryej001,Jeff Frye,4,nixot001,Trot Nixon,9,beltc001,Carlos Beltran,8,randj002,Joe Randa,5,damoj001,Johnny Damon,7,kingj001,Jeff King,3,suttl001,Larry Sutton,10,dye-j001,Jermaine Dye,9,kreuc001,Chad Kreuter,2,sancr001,Rey Sanchez,6,feblc001,Carlos Febles,4,NaN,Y
3,19990405,0,Mon,NYA,AL,1,OAK,AL,1,3,5,48,N,NaN,NaN,NaN,OAK01,46380,160,10100010,2030,29,5,0,0,2,3,0,0,1,4,0,6,0,1,0,0,7,3,5,5,0,0,24,8,0,0,0,0,31,7,1,0,1,5,0,0,0,5,0,8,1,0,0,0,7,2,2,2,0,0,24,10,1,0,0,0,evanj901,Jim Evans,mccol901,Larry McCoy,meric901,Chuck Meriwether,fordd901,Dale Ford,NaN,(none),NaN,(none),zimmd101,Don Zimmer,howea001,Art Howe,matht002,T.J. Mathews,stanm003,Mike Stanton,NaN,(none),staim001,Matt Stairs,clemr001,Roger Clemens,hereg001,Gil Heredia,knobc001,Chuck Knoblauch,4,jeted001,Derek Jeter,6,oneip001,Paul O'Neill,9,willb002,Bernie Williams,8,martt002,Tino Martinez,3,davic001,Chili Davis,10,leder001,Ricky Ledee,7,bross001,Scott Brosius,5,giraj001,Joe Girardi,2,philt001,Tony Phillips,4,mcdoj002,Jason McDonald,8,giamj001,Jason Giambi,10,staim001,Matt Stairs,9,jahaj001,John Jaha,3,grieb001,Ben Grieve,7,chave001,Eric Chavez,5,hinca001,A.J. Hinch,2,tejam001,Miguel Tejada,6,NaN,Y
4,19990405,0,Mon,CHA,AL,1,SEA,AL,1,8,2,54,N,NaN,NaN,NaN,SEA02,51656,154,100122200,2000000,36,12,2,1,2,7,0,0,0,2,0,3,0,0,3,0,3,3,2,2,0,0,27,8,0,0,0,0,34,8,1,0,2,2,0,0,0,3,0,8,0,0,0,0,8,2,8,8,0,0,27,15,0,0,3,0,brinj901,Joe Brinkman,shulj901,John Shulock,scotd901,Dale Scott,cousd901,Derryl Cousins,NaN,(none),NaN,(none),manuj101,Jerry Manuel,pinil001,Lou Piniella,baldj002,James Baldwin,fassj001,Jeff Fassero,NaN,(none),jackd002,Darrin Jackson,baldj002,James Baldwin,fassj001,Jeff Fassero,durhr001,Ray Durham,4,carum001,Mike Caruso,6,thomf001,Frank Thomas,3,konep001,Paul Konerko,10,ordom001,Magglio Ordonez,9,nortg001,Greg Norton,5,abboj002,Jeff Abbott,7,jackd002,Darrin Jackson,8,fordb001,Brook Fordyce,2,guilc001,Carlos Guillen,4,rodra001,Alex Rodriguez,6,grifk002,Ken Griffey,8,marte001,Edgar Martinez,10,segud001,David Segui,3,buhnj001,Jay Buhner,9,mabrj001,John Mabry,7,davir002,Russ Davis,5,wilsd001,Dan Wilson,2,NaN,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12137,20030928,0,Sun,NYN,NL,161,FLO,NL,162,0,4,51,D,NaN,NaN,NaN,MIA01,27529,132,0,10300000x,31,4,0,0,0,0,0,0,0,2,0,11,0,0,1,0,6,3,4,4,0,0,24,6,1,0,0,0,30,7,1,0,1,4,1,0,0,3,0,6,1,0,0,0,6,4,0,0,0,0,27,5,1,0,1,0,coope901,Eric Cooper,timmt901,Tim Timmons,reilm901,Mike Reilly,hohnb901,Bill Hohn,NaN,(none),NaN,(none),howea001,Art Howe,mckej801,Jack McKeon,willd003,Dontrelle Willis,grifj001,Jeremy Griffiths,NaN,(none),lee-d002,Derrek Lee,grifj001,Jeremy Griffiths,willd003,Dontrelle Willis,ceder001,Roger Cedeno,9,bellj001,Jay Bell,4,wiggt001,Ty Wigginton,5,clart002,Tony Clark,3,gonzr002,Raul Gonzalez,7,wilsv001,Vance Wilson,2,mcewj001,Joe McEwing,8,velaj001,Jorge Velandia,6,grifj001,Jeremy Griffiths,1,pierj002,Juan Pierre,8,mordm001,Mike Mordecai,4,lowem001,Mike Lowell,5,lee-d002,Derrek Lee,3,encaj001,Juan Encarnacion,9,conij001,Jeff Conine,7,gonza002,Alex Gonzalez,6,redmm001,Mike Redmond,2,willd003,Dontrelle Willis,1,NaN,Y
12138,20030928,0,Sun,MIL,NL,162,HOU,NL,162,5,8,51,D,NaN,NaN,NaN,HOU03,37977,152,100001012,10320020x,36,8,4,1,1,5,0,0,0,2,0,13,0,0,1,0,6,5,8,8,0,0,24,5,1,0,1,0,34,10,1,0,4,8,0,0,0,1,0,6,0,0,1,0,3,6,4,4,1,0,27,8,2,0,1,0,wintm901,Mike Winters,froeb901,Bruce Froemming,eddid901,Doug Eddings,kulpr901,Ron Kulpa,NaN,(none),NaN,(none),yoste001,Ned Yost,willj107,Jimy Williams,stonr001,Ricky Stone,martl001,Luis Martinez,NaN,(none),bagwj001,Jeff Bagwell,martl001,Luis Martinez,saark001,Kirk Saarloos,podss001,Scott Podsednik,8,contj001,Jason Conti,9,zoccp001,Peter Zoccolillo,7,sexsr001,Richie Sexson,3,helmw001,Wes Helms,5,osikk001,Keith Osik,2,weekr001,Rickie Weeks,4,cruze001,Enrique Cruz,6,martl001,Luis Martinez,1,lanej001,Jason Lane,8,ensbm001,Morgan Ensberg,5,bagwj001,Jeff Bagwell,3,kentj001,Jeff Kent,4,hidar001,Richard Hidalgo,9,berkl001,Lance Berkman,7,ausmb001,Brad Ausmus,2,evera001,Adam Everett,6,saark001,Kirk Saarloos,1,NaN,Y
12139,20030928,0,Sun,ATL,NL,162,PHI,NL,162,5,2,54,D,NaN,NaN,NaN,PHI12,58554,171,10310000,101000000,36,13,3,0,0,5,1,2,0,1,0,8,0,0,0,0,8,5,2,2,2,0,27,11,0,0,1,0,33,8,3,0,0,2,0,0,0,1,0,4,1,0,1,0,5,5,5,5,0,0,27,8,1,0,0,0,crawj901,Jerry Crawford,onorb901,Brian O'Nora,cuzzp901,Phil Cuzzi,poncl901,Larry Poncino,NaN,(none),NaN,(none),cox-b103,Bobby Cox,bowal001,Larry Bowa,maddg002,Greg Maddux,millk004,Kevin Millwood,marqj001,Jason Marquis,furcr001,Rafael Furcal,maddg002,Greg Maddux,millk004,Kevin Millwood,furcr001,Rafael Furcal,6,gilem001,Marcus Giles,4,shefg001,Gary Sheffield,9,jonec004,Chipper Jones,7,jonea002,Andruw Jones,8,lopej001,Javy Lopez,2,fickr001,Robert Fick,3,derom001,Mark DeRosa,5,maddg002,Greg Maddux,1,byrdm001,Marlon Byrd,8,rollj001,Jimmy Rollins,6,abreb001,Bobby Abreu,9,thomj002,Jim Thome,3,liebm001,Mike Lieberthal,2,burrp001,Pat Burrell,7,utlec001,Chase Utley,4,peret003,Tomas Perez,5,millk004,Kevin Millwood,1,NaN,Y
12140,20030928,0,Sun,COL,NL,162,SDN,NL,162,10,8,54,D,NaN,NaN,NaN,SAN01,60988,184,30000520,100130210,37,11,1,0,4,10,1,0,0,5,1,11,0,0,0,0,6,6,8,8,0,0,27,15,1,0,2,0,37,13,2,1,2,8,0,1,3,3,0,5,1,0,2,0,9,6,10,10,0,0,27,8,0,0,0,0,rungb901,Brian Runge,kellk901,Kevin Kelley,culbf901,Fieldin Culbreth,drakr901,Rob Drake,NaN,(none),NaN,(none),hurdc001,Clint Hurdle,bochb002,Bruce Bochy,lopej002,Javier Lopez,witaj001,Jay Witasick,speij001,Justin Speier,paytj001,Jay Payton,olivd001,Darren Oliver,peavj001,Jake Peavy,bellr002,Ronnie Belliard,4,stync001,Chris Stynes,5,heltt001,Todd Helton,3,paytj001,Jay Payton,7,walkl001,Larry Walker,9,reyer001,Rene Reyes,8,johnc002,Charles Johnson,2,uribj002,Juan Uribe,6,olivd001,Darren Oliver,1,burrs001,Sean Burroughs,5,lorem001,Mark Loretta,4,gileb002,Brian Giles,7,nevip001,Phil Nevin,3,kotsm001,Mark Kotsay,8,nadyx001,Xavier Nady,9,greek002,Khalil Greene,6,benng001,Gary Bennett,2,peavj001,Jake Peavy,1,NaN,Y
12141,20030928,0,Sun,LAN,NL,162,SFN,NL,161,3,12,51,D,NaN,NaN,NaN,SFO03,42142,163,110100000,52000302x,35,9,3,0,0,3,0,0,1,4,0,7,1,0,2,0,10,6,9,9,1,0,24,6,2,0,1,0,38,14,3,1,2,10,0,0,1,2,0,10,2,0,1,0,5,3,3,3,0,0,27,8,1,0,2,0,mealj901,Jerry Meals,guccc901,Chris Guccione,ripps901,Steve Rippley,vanol901,Larry Vanover,NaN,(none),NaN,(none),tracj101,Jim Tracy,alouf101,Felipe Alou,corrk001,Kevin Correia,alvaw001,Wilson Alvarez,NaN,(none),alfoe001,Edgardo Alfonzo,alvaw001,Wilson Alvarez,corrk001,Kevin Correia,iztuc001,Cesar Izturis,6,cabrj002,Jolbert Cabrera,8,grees001,Shawn Green,9,ventr001,Robin Ventura,3,belta001,Adrian Beltre,5,burnj001,Jeromy Burnitz,7,rossd001,David Ross,2,coraa001,Alex Cora,4,alvaw001,Wilson Alvarez,1,durhr001,Ray Durham,4,snowj001,J.T. Snow,3,aurir001,Rich Aurilia,6,bondb001,Barry Bonds,7,alfoe001,Edgardo Alfonzo,5,hammj001,Jeffrey Hammonds,8,cruzj004,Jose Cruz,9,torry001,Yorvit Torrealba,2,corrk001,Kevin Correia,1,NaN,Y

In [6]:
df['Hwin'] = df['home_score'] > df['visitor_score']
df['Awin'] = df['visitor_score'] > df['home_score']

In [7]:
dates = np.array(df['date'].astype(str), dtype='U')
lengths = np.char.str_len(dates)
np.unique(lengths)

# Shows first 4 chars are Year

array([8])

In [8]:
df['date'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 12142 entries, 0 to 12141
Series name: date
Non-Null Count  Dtype
--------------  -----
12142 non-null  int64
dtypes: int64(1)
memory usage: 95.0 KB

In [9]:
df['year'] = df['date'].astype(str).str[:4]
df['year'] = pd.to_datetime(df['year']).dt.year
df[['date', 'year']]

           date  year
0      19990404  1999
1      19990405  1999
2      19990405  1999
3      19990405  1999
4      19990405  1999
...         ...   ...
12137  20030928  2003
12138  20030928  2003
12139  20030928  2003
12140  20030928  2003
12141  20030928  2003

[12142 rows x 2 columns]

In [10]:
cols_to_aggregate = [
    'home_ab', 'home_h', 'home_2b', 'home_3b', 'home_hr',
    'home_bb', 'home_hbp', 'home_sf',
    'visitor_ab', 'visitor_h', 'visitor_2b', 'visitor_3b',
    'visitor_hr', 'visitor_bb', 'visitor_hbp', 'visitor_sf',
    'Hwin', 'Awin'
]

for col in cols_to_aggregate:
    if col in list(df.columns):
        continue
    else: print(f'{col} not found in df')

In [11]:
home_df = df.groupby(['year', 'home'])[cols_to_aggregate].sum().reset_index()
home_df = home_df.rename(columns={'home': 'Team'})

visitor_df = df.groupby(['year', 'visitor'])[cols_to_aggregate].sum().reset_index()
visitor_df = visitor_df.rename(columns={'visitor': 'Team'})

In [12]:
# Season Table

season_df = pd.merge(home_df, visitor_df, on=['year', 'Team'])
season_df

,year,Team,home_ab_x,home_h_x,home_2b_x,home_3b_x,home_hr_x,home_bb_x,home_hbp_x,home_sf_x,visitor_ab_x,visitor_h_x,visitor_2b_x,visitor_3b_x,visitor_hr_x,visitor_bb_x,visitor_hbp_x,visitor_sf_x,Hwin_x,Awin_x,home_ab_y,home_h_y,home_2b_y,home_3b_y,home_hr_y,home_bb_y,home_hbp_y,home_sf_y,visitor_ab_y,visitor_h_y,visitor_2b_y,visitor_3b_y,visitor_hr_y,visitor_bb_y,visitor_hbp_y,visitor_sf_y,Hwin_y,Awin_y
0,1999,ANA,2666,669,118,13,74,267,23,21,2832,762,151,10,105,322,27,39,37,44,2645,710,134,15,72,302,29,26,2828,735,130,9,84,244,20,21,48,33
1,1999,ARI,2730,754,142,31,101,285,17,31,2814,693,132,22,84,256,27,16,52,29,2751,694,123,12,92,287,22,14,2928,812,147,15,115,303,31,29,33,48
2,1999,ATL,2668,704,158,9,86,286,22,28,2798,674,107,10,75,221,10,19,56,25,2772,724,131,9,67,286,16,22,2901,777,151,14,111,322,31,19,34,47
3,1999,BAL,2732,762,136,9,98,315,36,32,2827,760,112,15,101,329,30,27,41,40,2638,708,157,19,97,318,19,22,2905,810,163,12,105,300,25,23,44,37
4,1999,BOS,2722,793,177,20,80,305,30,29,2820,722,149,10,72,226,32,20,49,32,2704,674,134,10,88,243,23,23,2857,758,157,22,96,292,25,27,36,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,2003,SFN,2704,751,134,19,82,306,14,21,2797,692,135,19,61,261,20,27,57,24,2590,657,124,12,75,285,23,26,2752,689,147,10,98,287,26,18,37,43
146,2003,SLN,2758,799,183,11,85,280,39,24,2857,729,155,14,93,232,28,18,48,33,2831,815,180,16,117,276,37,27,2914,781,159,21,111,300,34,30,44,37
147,2003,TBA,2795,752,158,21,56,232,29,21,2839,735,156,14,96,322,63,35,36,45,2663,719,163,17,100,317,32,30,2859,749,140,17,81,188,27,29,54,27
148,2003,TEX,2787,798,141,23,140,246,34,27,2929,855,197,20,105,284,39,22,43,38,2719,770,154,17,103,319,24,34,2877,708,133,13,99,242,41,15,53,28
149,2003,TOR,2763,779,191,16,94,284,40,28,2930,827,172,19,107,244,33,20,41,40,2730,733,128,23,77,241,24,18,2898,801,166,17,96,262,50,28,36,45

In [13]:
# Sanity Check

check_col_string = 'ab'
check_cols = []

for col in season_df.columns:
    if check_col_string in col:
        check_cols.append(col)

season_df[check_cols]

     home_ab_x  visitor_ab_x  home_ab_y  visitor_ab_y
0         2666          2832       2645          2828
1         2730          2814       2751          2928
2         2668          2798       2772          2901
3         2732          2827       2638          2905
4         2722          2820       2704          2857
..         ...           ...        ...           ...
145       2704          2797       2590          2752
146       2758          2857       2831          2914
147       2795          2839       2663          2859
148       2787          2929       2719          2877
149       2763          2930       2730          2898

[150 rows x 4 columns]

This isn't clear which metric is for current team, and which for opposition.

Solution: Alias Columns Correctly

In [14]:
list(season_df.columns)

['year',
 'Team',
 'home_ab_x',
 'home_h_x',
 'home_2b_x',
 'home_3b_x',
 'home_hr_x',
 'home_bb_x',
 'home_hbp_x',
 'home_sf_x',
 'visitor_ab_x',
 'visitor_h_x',
 'visitor_2b_x',
 'visitor_3b_x',
 'visitor_hr_x',
 'visitor_bb_x',
 'visitor_hbp_x',
 'visitor_sf_x',
 'Hwin_x',
 'Awin_x',
 'home_ab_y',
 'home_h_y',
 'home_2b_y',
 'home_3b_y',
 'home_hr_y',
 'home_bb_y',
 'home_hbp_y',
 'home_sf_y',
 'visitor_ab_y',
 'visitor_h_y',
 'visitor_2b_y',
 'visitor_3b_y',
 'visitor_hr_y',
 'visitor_bb_y',
 'visitor_hbp_y',
 'visitor_sf_y',
 'Hwin_y',
 'Awin_y']

In [15]:
for_metrics = [('home', 'x'), ('visitor', 'y')]
against_metrics = [('home', 'y'), ('visitor', 'x')]
rename_map = {}

for col in season_df.columns:
    if 'home' not in str(col) and 'visitor' not in str(col):
        continue
    
    if for_metrics[0][0] in col and for_metrics[0][1] in col:
        new_name = str(col).replace('x', 'for')
    if for_metrics[1][0] in col and for_metrics[1][1] in col:
        new_name = str(col).replace('y', 'for')

    if against_metrics[0][0] in col and against_metrics[0][1] in col:
        new_name = str(col).replace('y', 'against')
    if against_metrics[1][0] in col and against_metrics[1][1] in col:
        new_name = str(col).replace('x', 'against')

    rename_map[col] = new_name

keys_to_delete = []

for key in rename_map.keys():
    if 'home' not in str(key) and 'visitor' not in str(key):
        keys_to_delete.append(str(key))

for key in keys_to_delete:
    del rename_map[key]

rename_map

season_df = season_df.rename(columns=rename_map)

season_df

,year,Team,home_ab_for,home_h_for,home_2b_for,home_3b_for,home_hr_for,home_bb_for,home_hbp_for,home_sf_for,visitor_ab_against,visitor_h_against,visitor_2b_against,visitor_3b_against,visitor_hr_against,visitor_bb_against,visitor_hbp_against,visitor_sf_against,Hwin_x,Awin_x,home_ab_against,home_h_against,home_2b_against,home_3b_against,home_hr_against,home_bb_against,home_hbp_against,home_sf_against,visitor_ab_for,visitor_h_for,visitor_2b_for,visitor_3b_for,visitor_hr_for,visitor_bb_for,visitor_hbp_for,visitor_sf_for,Hwin_y,Awin_y
0,1999,ANA,2666,669,118,13,74,267,23,21,2832,762,151,10,105,322,27,39,37,44,2645,710,134,15,72,302,29,26,2828,735,130,9,84,244,20,21,48,33
1,1999,ARI,2730,754,142,31,101,285,17,31,2814,693,132,22,84,256,27,16,52,29,2751,694,123,12,92,287,22,14,2928,812,147,15,115,303,31,29,33,48
2,1999,ATL,2668,704,158,9,86,286,22,28,2798,674,107,10,75,221,10,19,56,25,2772,724,131,9,67,286,16,22,2901,777,151,14,111,322,31,19,34,47
3,1999,BAL,2732,762,136,9,98,315,36,32,2827,760,112,15,101,329,30,27,41,40,2638,708,157,19,97,318,19,22,2905,810,163,12,105,300,25,23,44,37
4,1999,BOS,2722,793,177,20,80,305,30,29,2820,722,149,10,72,226,32,20,49,32,2704,674,134,10,88,243,23,23,2857,758,157,22,96,292,25,27,36,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,2003,SFN,2704,751,134,19,82,306,14,21,2797,692,135,19,61,261,20,27,57,24,2590,657,124,12,75,285,23,26,2752,689,147,10,98,287,26,18,37,43
146,2003,SLN,2758,799,183,11,85,280,39,24,2857,729,155,14,93,232,28,18,48,33,2831,815,180,16,117,276,37,27,2914,781,159,21,111,300,34,30,44,37
147,2003,TBA,2795,752,158,21,56,232,29,21,2839,735,156,14,96,322,63,35,36,45,2663,719,163,17,100,317,32,30,2859,749,140,17,81,188,27,29,54,27
148,2003,TEX,2787,798,141,23,140,246,34,27,2929,855,197,20,105,284,39,22,43,38,2719,770,154,17,103,319,24,34,2877,708,133,13,99,242,41,15,53,28
149,2003,TOR,2763,779,191,16,94,284,40,28,2930,827,172,19,107,244,33,20,41,40,2730,733,128,23,77,241,24,18,2898,801,166,17,96,262,50,28,36,45

In [16]:
wins = ['Hwin_x', 'Awin_y']
loss = ['Hwin_y', 'Awin_x']

season_df = season_df.rename(
    columns = {
        'Hwin_x': 'Hwin', 
        'Awin_y': 'Awin', 
        'Hwin_y': 'Aloss',
        'Awin_x': 'Hloss'})

season_df['Total_Wins'] = season_df['Hwin'] + season_df['Awin']
season_df['Total_Losses'] = season_df['Hloss'] + season_df['Aloss']

season_df

,year,Team,home_ab_for,home_h_for,home_2b_for,home_3b_for,home_hr_for,home_bb_for,home_hbp_for,home_sf_for,visitor_ab_against,visitor_h_against,visitor_2b_against,visitor_3b_against,visitor_hr_against,visitor_bb_against,visitor_hbp_against,visitor_sf_against,Hwin,Hloss,home_ab_against,home_h_against,home_2b_against,home_3b_against,home_hr_against,home_bb_against,home_hbp_against,home_sf_against,visitor_ab_for,visitor_h_for,visitor_2b_for,visitor_3b_for,visitor_hr_for,visitor_bb_for,visitor_hbp_for,visitor_sf_for,Aloss,Awin,Total_Wins,Total_Losses
0,1999,ANA,2666,669,118,13,74,267,23,21,2832,762,151,10,105,322,27,39,37,44,2645,710,134,15,72,302,29,26,2828,735,130,9,84,244,20,21,48,33,70,92
1,1999,ARI,2730,754,142,31,101,285,17,31,2814,693,132,22,84,256,27,16,52,29,2751,694,123,12,92,287,22,14,2928,812,147,15,115,303,31,29,33,48,100,62
2,1999,ATL,2668,704,158,9,86,286,22,28,2798,674,107,10,75,221,10,19,56,25,2772,724,131,9,67,286,16,22,2901,777,151,14,111,322,31,19,34,47,103,59
3,1999,BAL,2732,762,136,9,98,315,36,32,2827,760,112,15,101,329,30,27,41,40,2638,708,157,19,97,318,19,22,2905,810,163,12,105,300,25,23,44,37,78,84
4,1999,BOS,2722,793,177,20,80,305,30,29,2820,722,149,10,72,226,32,20,49,32,2704,674,134,10,88,243,23,23,2857,758,157,22,96,292,25,27,36,45,94,68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,2003,SFN,2704,751,134,19,82,306,14,21,2797,692,135,19,61,261,20,27,57,24,2590,657,124,12,75,285,23,26,2752,689,147,10,98,287,26,18,37,43,100,61
146,2003,SLN,2758,799,183,11,85,280,39,24,2857,729,155,14,93,232,28,18,48,33,2831,815,180,16,117,276,37,27,2914,781,159,21,111,300,34,30,44,37,85,77
147,2003,TBA,2795,752,158,21,56,232,29,21,2839,735,156,14,96,322,63,35,36,45,2663,719,163,17,100,317,32,30,2859,749,140,17,81,188,27,29,54,27,63,99
148,2003,TEX,2787,798,141,23,140,246,34,27,2929,855,197,20,105,284,39,22,43,38,2719,770,154,17,103,319,24,34,2877,708,133,13,99,242,41,15,53,28,71,91
149,2003,TOR,2763,779,191,16,94,284,40,28,2930,827,172,19,107,244,33,20,41,40,2730,733,128,23,77,241,24,18,2898,801,166,17,96,262,50,28,36,45,86,76

In [17]:
season_df['Total_Games'] = season_df['Total_Wins'] + season_df['Total_Losses']

In [18]:
season_df['W_perc'] = season_df['Total_Wins'] / season_df['Total_Games']

In [19]:
season_df[['year', 'Team', 'Total_Wins', 'Total_Games', 'W_perc']].head(10)

   year Team  Total_Wins  Total_Games    W_perc
0  1999  ANA          70          162  0.432099
1  1999  ARI         100          162  0.617284
2  1999  ATL         103          162  0.635802
3  1999  BAL          78          162  0.481481
4  1999  BOS          94          162  0.580247
5  1999  CHA          75          161  0.465839
6  1999  CHN          67          162  0.413580
7  1999  CIN          96          163  0.588957
8  1999  CLE          97          162  0.598765
9  1999  COL          72          162  0.444444

In [20]:
# OBP: On Base Percentage

OBP_FOR_COLS = [
    'home_h_x', 
    'visitor_h_y', 
    'home_bb_x', 
    'visitor_bb_y', 
    'home_hbp_x', 
    'visitor_hbp_y',
    'home_ab_x', 
    'visitor_ab_y', 
    'home_bb_x', 
    'visitor_bb_y', 
    'home_hbp_x', 
    'visitor_hbp_y', 
    'home_sf_x', 
    'visitor_sf_y'
]

# OBP FOR FORMULA:
"""
('home_h_x' + 'visitor_h_y' + 'home_bb_x' + 
'visitor_bb_y' + 'home_hbp_x' + 'visitor_hbp_y')
/
('home_ab_x' + 'visitor_ab_y' + 'home_bb_x' + 'visitor_bb_y' + 
'home_hbp_x' + 'visitor_hbp_y' + 'home_sf_x' + 'visitor_sf_y')
"""

for i, col in enumerate(OBP_FOR_COLS):
    new = rename_map[col]
    OBP_FOR_COLS[i] = new

In [21]:
# First 6 cols in first part of bracket formula, Remaining 8 in second part - Check:
print(f'{OBP_FOR_COLS[0:6]}\n{OBP_FOR_COLS[6:]}')

['home_h_for', 'visitor_h_for', 'home_bb_for', 'visitor_bb_for', 'home_hbp_for', 'visitor_hbp_for']
['home_ab_for', 'visitor_ab_for', 'home_bb_for', 'visitor_bb_for', 'home_hbp_for', 'visitor_hbp_for', 'home_sf_for', 'visitor_sf_for']

In [22]:
dividend_mask = OBP_FOR_COLS[0:6]
divisor_mask = OBP_FOR_COLS[6:]

season_df['OBP_FOR'] = (season_df[dividend_mask].sum(axis=1)) / (season_df[divisor_mask].sum(axis=1))
season_df['OBP_FOR']

0      0.321511
1      0.346553
2      0.341246
3      0.353015
4      0.350406
         ...
145    0.338283
146    0.350055
147    0.319903
148    0.330037
149    0.348812
Name: OBP_FOR, Length: 150, dtype: float64

In [23]:
OBP_AGN_COLS = [
    'home_h_y', 'visitor_h_x', 'home_bb_y', 
    'visitor_bb_x', 'home_hbp_y', 'visitor_hbp_x',
    'home_ab_y', 'visitor_ab_x', 'home_bb_y', 'visitor_bb_x', 
    'home_hbp_y', 'visitor_hbp_x', 'home_sf_y', 'visitor_sf_x']

# OBP_AGN Formula
"""
('home_h_y' + 'visitor_h_x' + 'home_bb_y' + 
'visitor_bb_x' + 'home_hbp_y' + 'visitor_hbp_x')
/
('home_ab_y' + 'visitor_ab_x' + 'home_bb_y' + 'visitor_bb_x' + 
'home_hbp_y' + 'visitor_hbp_x' + 'home_sf_y' + 'visitor_sf_x')

"""

for i, col in enumerate(OBP_AGN_COLS):
    new = rename_map[col]
    OBP_AGN_COLS[i] = new

dividend_mask = OBP_AGN_COLS[0:6]
divisor_mask = OBP_AGN_COLS[6:]

season_df['OBP_AGN'] = (season_df[dividend_mask].sum(axis=1)) / (season_df[divisor_mask].sum(axis=1))
season_df.iloc[:, -2:]

      OBP_FOR   OBP_AGN
0    0.321511  0.345869
1    0.346553  0.319864
2    0.341246  0.314290
3    0.353015  0.348470
4    0.350406  0.315219
..        ...       ...
145  0.338283  0.321446
146  0.350055  0.335712
147  0.319903  0.347246
148  0.330037  0.359655
149  0.348812  0.336859

[150 rows x 2 columns]

In [24]:
# SLG: Slugging Percentage:
# The average number of bases the team gains per at-bat

# Formula:
"""
((home_h_x + visitor_h_y) - (home_2b_x + visitor_2b_y) - 
(home_3b_x + visitor_3b_y) - (home_hr_x + visitor_hr_y) +

    2 * (home_2b_x + visitor_2b_y) +
    3 * (home_3b_x + visitor_3b_y) +
    4 * (home_hr_x + visitor_hr_y) ) 
/ 
(home_ab_x + visitor_ab_y)

"""

SLG_FOR_COLS = [
    'home_h_x',
    'visitor_h_y',
    'home_2b_x',
    'visitor_2b_y',
    'home_3b_x',
    'visitor_3b_y',
    'home_hr_x',
    'visitor_hr_y',
    'home_2b_x',
    'visitor_2b_y',
    'home_3b_x',
    'visitor_3b_y',
    'home_hr_x',
    'visitor_hr_y',
    'home_ab_x',
    'visitor_ab_y'
    ]

for i, col in enumerate(SLG_FOR_COLS):
    new_name = rename_map[col]
    SLG_FOR_COLS[i] = new_name

pos_dict = {}

# For ease of use print cols with table name:
for i, col in enumerate(SLG_FOR_COLS):
    pos_dict[i] = f"""season_df['{col}']"""


print(f"""
(({pos_dict[0]} + {pos_dict[1]}) - ({pos_dict[2]} + {pos_dict[3]}) - 
({pos_dict[4]} + {pos_dict[5]}) - ({pos_dict[6]} + {pos_dict[7]}) +
    2 * ({pos_dict[8]} + {pos_dict[9]}) +
    3 * ({pos_dict[10]} + {pos_dict[11]}) +
    4 * ({pos_dict[12]} + {pos_dict[13]}) ) 
/ 
({pos_dict[14]} + {pos_dict[15]})
      """)

((season_df['home_h_for'] + season_df['visitor_h_for']) - (season_df['home_2b_for'] + season_df['visitor_2b_for']) -
(season_df['home_3b_for'] + season_df['visitor_3b_for']) - (season_df['home_hr_for'] + season_df['visitor_hr_for']) +
    2 * (season_df['home_2b_for'] + season_df['visitor_2b_for']) +
    3 * (season_df['home_3b_for'] + season_df['visitor_3b_for']) +
    4 * (season_df['home_hr_for'] + season_df['visitor_hr_for']) )
/
(season_df['home_ab_for'] + season_df['visitor_ab_for'])

In [25]:
season_df['SLG_FOR'] = (
    (season_df['home_h_for'] + season_df['visitor_h_for']) - (season_df['home_2b_for'] + season_df['visitor_2b_for']) - 
    (season_df['home_3b_for'] + season_df['visitor_3b_for']) - (season_df['home_hr_for'] + season_df['visitor_hr_for']) +
    2 * (season_df['home_2b_for'] + season_df['visitor_2b_for']) +
    3 * (season_df['home_3b_for'] + season_df['visitor_3b_for']) +
    4 * (season_df['home_hr_for'] + season_df['visitor_hr_for'])) /(season_df['home_ab_for'] + season_df['visitor_ab_for'])

In [26]:
season_df['SLG_AGN'] = (
    (season_df['home_h_against'] + season_df['visitor_h_against']) - (season_df['home_2b_against'] + season_df['visitor_2b_against']) - 
    (season_df['home_3b_against'] + season_df['visitor_3b_against']) - (season_df['home_hr_against'] + season_df['visitor_hr_against']) +
    2 * (season_df['home_2b_against'] + season_df['visitor_2b_against']) +
    3 * (season_df['home_3b_against'] + season_df['visitor_3b_against']) +
    4 * (season_df['home_hr_against'] + season_df['visitor_hr_against'])) /(season_df['home_ab_against'] + season_df['visitor_ab_against'])

In [27]:
season_df.iloc[:, -4:]

      OBP_FOR   OBP_AGN   SLG_FOR   SLG_AGN
0    0.321511  0.345869  0.394976  0.426876
1    0.346553  0.319864  0.458643  0.402156
2    0.341246  0.314290  0.435805  0.377020
3    0.353015  0.348470  0.447401  0.438975
4    0.350406  0.315219  0.447571  0.398081
..        ...       ...       ...       ...
145  0.338283  0.321446  0.425037  0.385743
146  0.350055  0.335712  0.453808  0.451653
147  0.319903  0.347246  0.404316  0.440385
148  0.330037  0.359655  0.453566  0.473442
149  0.348812  0.336859  0.454513  0.440989

[150 rows x 4 columns]

In [ ]:
season_df

,year,Team,home_ab_for,home_h_for,home_2b_for,home_3b_for,home_hr_for,home_bb_for,home_hbp_for,home_sf_for,visitor_ab_against,visitor_h_against,visitor_2b_against,visitor_3b_against,visitor_hr_against,visitor_bb_against,visitor_hbp_against,visitor_sf_against,Hwin,Hloss,home_ab_against,home_h_against,home_2b_against,home_3b_against,home_hr_against,home_bb_against,home_hbp_against,home_sf_against,visitor_ab_for,visitor_h_for,visitor_2b_for,visitor_3b_for,visitor_hr_for,visitor_bb_for,visitor_hbp_for,visitor_sf_for,Aloss,Awin,Total_Wins,Total_Losses,Total_Games,W_perc,OBP_FOR,OBP_AGN,SLG_FOR,SLG_AGN
0,1999,ANA,2666,669,118,13,74,267,23,21,2832,762,151,10,105,322,27,39,37,44,2645,710,134,15,72,302,29,26,2828,735,130,9,84,244,20,21,48,33,70,92,162,0.432099,0.321511,0.345869,0.394976,0.426876
1,1999,ARI,2730,754,142,31,101,285,17,31,2814,693,132,22,84,256,27,16,52,29,2751,694,123,12,92,287,22,14,2928,812,147,15,115,303,31,29,33,48,100,62,162,0.617284,0.346553,0.319864,0.458643,0.402156
2,1999,ATL,2668,704,158,9,86,286,22,28,2798,674,107,10,75,221,10,19,56,25,2772,724,131,9,67,286,16,22,2901,777,151,14,111,322,31,19,34,47,103,59,162,0.635802,0.341246,0.314290,0.435805,0.377020
3,1999,BAL,2732,762,136,9,98,315,36,32,2827,760,112,15,101,329,30,27,41,40,2638,708,157,19,97,318,19,22,2905,810,163,12,105,300,25,23,44,37,78,84,162,0.481481,0.353015,0.348470,0.447401,0.438975
4,1999,BOS,2722,793,177,20,80,305,30,29,2820,722,149,10,72,226,32,20,49,32,2704,674,134,10,88,243,23,23,2857,758,157,22,96,292,25,27,36,45,94,68,162,0.580247,0.350406,0.315219,0.447571,0.398081
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,2003,SFN,2704,751,134,19,82,306,14,21,2797,692,135,19,61,261,20,27,57,24,2590,657,124,12,75,285,23,26,2752,689,147,10,98,287,26,18,37,43,100,61,161,0.621118,0.338283,0.321446,0.425037,0.385743
146,2003,SLN,2758,799,183,11,85,280,39,24,2857,729,155,14,93,232,28,18,48,33,2831,815,180,16,117,276,37,27,2914,781,159,21,111,300,34,30,44,37,85,77,162,0.524691,0.350055,0.335712,0.453808,0.451653
147,2003,TBA,2795,752,158,21,56,232,29,21,2839,735,156,14,96,322,63,35,36,45,2663,719,163,17,100,317,32,30,2859,749,140,17,81,188,27,29,54,27,63,99,162,0.388889,0.319903,0.347246,0.404316,0.440385
148,2003,TEX,2787,798,141,23,140,246,34,27,2929,855,197,20,105,284,39,22,43,38,2719,770,154,17,103,319,24,34,2877,708,133,13,99,242,41,15,53,28,71,91,162,0.438272,0.330037,0.359655,0.453566,0.473442
149,2003,TOR,2763,779,191,16,94,284,40,28,2930,827,172,19,107,244,33,20,41,40,2730,733,128,23,77,241,24,18,2898,801,166,17,96,262,50,28,36,45,86,76,162,0.530864,0.348812,0.336859,0.454513,0.440989

In [30]:
season_df[
    (season_df['year'] == 1999) &
    (season_df['Team'] == 'ANA')
]

,year,Team,home_ab_for,home_h_for,home_2b_for,home_3b_for,home_hr_for,home_bb_for,home_hbp_for,home_sf_for,visitor_ab_against,visitor_h_against,visitor_2b_against,visitor_3b_against,visitor_hr_against,visitor_bb_against,visitor_hbp_against,visitor_sf_against,Hwin,Hloss,home_ab_against,home_h_against,home_2b_against,home_3b_against,home_hr_against,home_bb_against,home_hbp_against,home_sf_against,visitor_ab_for,visitor_h_for,visitor_2b_for,visitor_3b_for,visitor_hr_for,visitor_bb_for,visitor_hbp_for,visitor_sf_for,Aloss,Awin,Total_Wins,Total_Losses,Total_Games,W_perc,OBP_FOR,OBP_AGN,SLG_FOR,SLG_AGN
0,1999,ANA,2666,669,118,13,74,267,23,21,2832,762,151,10,105,322,27,39,37,44,2645,710,134,15,72,302,29,26,2828,735,130,9,84,244,20,21,48,33,70,92,162,0.432099,0.321511,0.345869,0.394976,0.426876

In [ ]:
# Q1 - Median Wins Per Season

median_wins = season_df.groupby('year')['Total_Wins'].median()
median_wins

year
1999    77.5
2000    82.0
2001    82.0
2002    79.5
2003    84.5
Name: Total_Wins, dtype: float64

In [36]:
# Question 2
# Aggregate (sum) the number of home team hits for every individual season in the data. 
# Which season did the minimum aggregate home team hit count occur?

home_hits = season_df.groupby('year')['home_h_for'].sum()
home_hits

year
1999    22340
2000    22401
2001    21740
2002    21484
2003    21935
Name: home_h_for, dtype: int64

In [ ]:
#Q3 - Rank the seasons from highest to lowest average number of at bats for the away teams aggregated over the entire season. 

visitor_atbats = season_df.groupby('year')['visitor_ab_for'].sum().sort_values(ascending=False)
visitor_atbats

year
2000    85660
1999    85562
2003    85348
2001    85034
2002    84696
Name: visitor_ab_for, dtype: int64

In [ ]:
"""
Create batting average for and batting average against as the sum the relevant statistics for each team as home team and visiting team.

Create the win percentage variable for each team by generating a count of games played and dividing total wins by total games played.

Using a similar process to part 2), calculate each team’s home and away win percentage separately for each season. 

Merge each team’s home and away win percentage for each season into one data frame. Calculate WPCT diff defined as:
- home win percentage –
- away win percentage for every team in each season
"""

In [41]:
# Hits / AtBats

season_df['BA_for'] = (season_df['home_h_for'] + season_df['visitor_h_for']) / (season_df['home_ab_for'] + season_df['visitor_ab_for'])
season_df['BA_against'] = (season_df['home_h_against'] + season_df['visitor_h_against']) / (season_df['home_ab_against'] + season_df['visitor_ab_against'])

In [43]:
# Home + Away Win pct

season_df['HWin_pct'] = season_df['Hwin'] / (season_df['Hwin'] + season_df['Hloss'])
season_df['AWin_pct'] = season_df['Awin'] / (season_df['Awin'] + season_df['Aloss'])

In [42]:
for col in season_df.columns:
    if str.lower('win') in col or str.lower('loss') in col:
        print(col)

Hwin
Hloss
Aloss
Awin

In [45]:
season_df['WPCT_diff'] = season_df['HWin_pct'] - season_df['AWin_pct']

In [46]:
season_df

,year,Team,home_ab_for,home_h_for,home_2b_for,home_3b_for,home_hr_for,home_bb_for,home_hbp_for,home_sf_for,visitor_ab_against,visitor_h_against,visitor_2b_against,visitor_3b_against,visitor_hr_against,visitor_bb_against,visitor_hbp_against,visitor_sf_against,Hwin,Hloss,home_ab_against,home_h_against,home_2b_against,home_3b_against,home_hr_against,home_bb_against,home_hbp_against,home_sf_against,visitor_ab_for,visitor_h_for,visitor_2b_for,visitor_3b_for,visitor_hr_for,visitor_bb_for,visitor_hbp_for,visitor_sf_for,Aloss,Awin,Total_Wins,Total_Losses,Total_Games,W_perc,OBP_FOR,OBP_AGN,SLG_FOR,SLG_AGN,BA_for,BA_against,HWin_pct,AWin_pct,WPCT_diff
0,1999,ANA,2666,669,118,13,74,267,23,21,2832,762,151,10,105,322,27,39,37,44,2645,710,134,15,72,302,29,26,2828,735,130,9,84,244,20,21,48,33,70,92,162,0.432099,0.321511,0.345869,0.394976,0.426876,0.255552,0.268760,0.456790,0.407407,0.049383
1,1999,ARI,2730,754,142,31,101,285,17,31,2814,693,132,22,84,256,27,16,52,29,2751,694,123,12,92,287,22,14,2928,812,147,15,115,303,31,29,33,48,100,62,162,0.617284,0.346553,0.319864,0.458643,0.402156,0.276776,0.249236,0.641975,0.592593,0.049383
2,1999,ATL,2668,704,158,9,86,286,22,28,2798,674,107,10,75,221,10,19,56,25,2772,724,131,9,67,286,16,22,2901,777,151,14,111,322,31,19,34,47,103,59,162,0.635802,0.341246,0.314290,0.435805,0.377020,0.265936,0.250987,0.691358,0.580247,0.111111
3,1999,BAL,2732,762,136,9,98,315,36,32,2827,760,112,15,101,329,30,27,41,40,2638,708,157,19,97,318,19,22,2905,810,163,12,105,300,25,23,44,37,78,84,162,0.481481,0.353015,0.348470,0.447401,0.438975,0.278872,0.268618,0.506173,0.456790,0.049383
4,1999,BOS,2722,793,177,20,80,305,30,29,2820,722,149,10,72,226,32,20,49,32,2704,674,134,10,88,243,23,23,2857,758,157,22,96,292,25,27,36,45,94,68,162,0.580247,0.350406,0.315219,0.447571,0.398081,0.278007,0.252715,0.604938,0.555556,0.049383
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,2003,SFN,2704,751,134,19,82,306,14,21,2797,692,135,19,61,261,20,27,57,24,2590,657,124,12,75,285,23,26,2752,689,147,10,98,287,26,18,37,43,100,61,161,0.621118,0.338283,0.321446,0.425037,0.385743,0.263930,0.250418,0.703704,0.537500,0.166204
146,2003,SLN,2758,799,183,11,85,280,39,24,2857,729,155,14,93,232,28,18,48,33,2831,815,180,16,117,276,37,27,2914,781,159,21,111,300,34,30,44,37,85,77,162,0.524691,0.350055,0.335712,0.453808,0.451653,0.278561,0.271449,0.592593,0.456790,0.135802
147,2003,TBA,2795,752,158,21,56,232,29,21,2839,735,156,14,96,322,63,35,36,45,2663,719,163,17,100,317,32,30,2859,749,140,17,81,188,27,29,54,27,63,99,162,0.388889,0.319903,0.347246,0.404316,0.440385,0.265476,0.264268,0.444444,0.333333,0.111111
148,2003,TEX,2787,798,141,23,140,246,34,27,2929,855,197,20,105,284,39,22,43,38,2719,770,154,17,103,319,24,34,2877,708,133,13,99,242,41,15,53,28,71,91,162,0.438272,0.330037,0.359655,0.453566,0.473442,0.265890,0.287712,0.530864,0.345679,0.185185
149,2003,TOR,2763,779,191,16,94,284,40,28,2930,827,172,19,107,244,33,20,41,40,2730,733,128,23,77,241,24,18,2898,801,166,17,96,262,50,28,36,45,86,76,162,0.530864,0.348812,0.336859,0.454513,0.440989,0.279103,0.275618,0.506173,0.555556,-0.049383

In [48]:
# Question 1
# Find the team with the maximum single season WPCT diff in the dataframe. What was this team’s away winning percentage for the season?

q1 = season_df.loc[season_df['WPCT_diff'] == season_df['WPCT_diff'].max(), 'AWin_pct']
q1

129    0.308642
Name: AWin_pct, dtype: float64

In [50]:
# Question 2
# Create a variable AVG Diff = 
# Batting Average For – Batting Average Against. What was the minimum (most negative) single season team AVG Diff in the dataframe?

season_df['BA_diff'] = season_df['BA_for'] - season_df['BA_against']
season_df['BA_diff'].min()

np.float64(-0.045685013851863465)

In [ ]:
# Q3: How many teams didn't play 162 games?

diff_game_count = season_df[
    season_df['Total_Games'] != 162
]

teams_diff_game_count = diff_game_count['Team'].nunique()

print(f'Unique Season/Team where not 162 games: {len(diff_game_count)}')
print(f'Number of Teams Not played 162 games: {teams_diff_game_count}')

Unique Season/Team where not 162 games: 27
Number of Teams Not played 162 games: 18

In [ ]:
# Assignment Part 3:

"""
Run an OLS (Ordinary Least Squares) regression of win percentage on batting average for and batting average against.

Run an OLS (Ordinary Least Squares) regression of win percentage on batting average for and batting average against,   
constraining the coefficient on each variable to be equal and opposite."""

In [62]:
import statsmodels.formula.api as smf

WinBA_lm = smf.ols(formula = 'W_perc ~ BA_for + BA_against', data=season_df).fit()
WinBA_lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 W_perc   R-squared:                       0.719
Model:                            OLS   Adj. R-squared:                  0.715
Method:                 Least Squares   F-statistic:                     187.8
Date:                Fri, 13 Mar 2026   Prob (F-statistic):           3.26e-41
Time:                        00:21:12   Log-Likelihood:                 265.31
No. Observations:                 150   AIC:                            -524.6
Df Residuals:                     147   BIC:                            -515.6
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.6031      0.099      6.070      0.000       0.407       0.799
BA_for         3.7843      0.301     12.582      0.000       3.190       4.379
BA_against    -4.1721      0.259    -16.114      0.000      -4.684      -3.660
==============================================================================
Omnibus:                        0.241   Durbin-Watson:                   2.270
Prob(Omnibus):                  0.887   Jarque-Bera (JB):                0.047
Skew:                           0.009   Prob(JB):                        0.977
Kurtosis:                       3.085   Cond. No.                         97.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [63]:
import statsmodels.formula.api as smf

WinBA_lm_constrained = smf.ols(formula = 'W_perc ~ BA_diff', data=season_df).fit()
WinBA_lm_constrained.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 W_perc   R-squared:                       0.717
Model:                            OLS   Adj. R-squared:                  0.715
Method:                 Least Squares   F-statistic:                     374.3
Date:                Fri, 13 Mar 2026   Prob (F-statistic):           2.29e-42
Time:                        00:28:26   Log-Likelihood:                 264.76
No. Observations:                 150   AIC:                            -525.5
Df Residuals:                     148   BIC:                            -519.5
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.4999      0.003    146.827      0.000       0.493       0.507
BA_diff        4.0108      0.207     19.347      0.000       3.601       4.420
==============================================================================
Omnibus:                        0.396   Durbin-Watson:                   2.232
Prob(Omnibus):                  0.820   Jarque-Bera (JB):                0.129
Skew:                           0.003   Prob(JB):                        0.938
Kurtosis:                       3.144   Cond. No.                         60.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""