## Part 1 - Data Preparation and Exploration

In [47]:
#Import Libraries

import pandas as pd
import datetime as dt
import scipy.stats as sp
import numpy as np
import statsmodels.formula.api as sm

In [48]:
# Import Shotlog_14_15 and Player_Stats Datasets

pd.set_option('display.max_columns', None)

Shotlog_1415=pd.read_csv("C:/Users/nickc/OneDrive/Documents/Projects/Sports Performance Analytics/Section 1/Hot Hand/Files/Shotlog_14_15.csv")
Player_Stats=pd.read_csv("C:/Users/nickc/OneDrive/Documents/Projects/Sports Performance Analytics/Section 1/Hot Hand/Files/Player_Stats_14_15.csv")
display(Shotlog_1415)

,game_id,date,match,home_team,away_team,home_away,result,final_margin,shot_number,quarter,game_clock,shot_clock,dribbles,touch_time,shot_dist,points,current_shot_outcome,closest_defender,closest_defender_id,closest_def_dist,current_shot_hit,points_earned,shoot_player,player_id,average_hit,shot_count,shot_per_game
0,21400280,5-Dec-14,ATL @ BKN,BKN,ATL,A,W,23,1,1,11:23,5.6,0,1.2,19.6,2,made,"Lopez, Brook",201572,6.6,1,2,al horford,201143,0.541259,715,10
1,21400280,5-Dec-14,ATL @ BKN,BKN,ATL,A,W,23,2,1,10:48,5.6,0,1.1,14.5,2,missed,"Lopez, Brook",201572,5.6,0,0,al horford,201143,0.541259,715,10
2,21400280,5-Dec-14,ATL @ BKN,BKN,ATL,A,W,23,3,1,9:40,11.0,0,0.4,5.8,2,missed,"Lopez, Brook",201572,4.7,0,0,al horford,201143,0.541259,715,10
3,21400280,5-Dec-14,ATL @ BKN,BKN,ATL,A,W,23,4,1,7:09,13.5,0,0.8,20.8,2,missed,"Lopez, Brook",201572,5.8,0,0,al horford,201143,0.541259,715,10
4,21400280,5-Dec-14,ATL @ BKN,BKN,ATL,A,W,23,5,2,5:49,12.9,0,0.9,20.1,2,missed,"Lopez, Brook",201572,6.4,0,0,al horford,201143,0.541259,715,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128064,21400350,14-Dec-14,WAS vs. UTA,WAS,UTA,H,W,9,11,3,2:59,21.1,3,4.0,1.7,2,made,"Burke, Trey",203504,4.7,1,2,john wall,202322,0.448513,874,15
128065,21400350,14-Dec-14,WAS vs. UTA,WAS,UTA,H,W,9,12,3,0:43,6.1,2,2.2,17.8,2,made,"Exum, Dante",203957,3.4,1,2,john wall,202322,0.448513,874,15
128066,21400350,14-Dec-14,WAS vs. UTA,WAS,UTA,H,W,9,13,4,2:18,4.3,0,0.0,3.2,2,missed,"Kanter, Enes",202683,1.2,0,0,john wall,202322,0.448513,874,15
128067,21400350,14-Dec-14,WAS vs. UTA,WAS,UTA,H,W,9,14,4,2:18,4.3,0,0.6,3.3,2,made,"Kanter, Enes",202683,1.4,1,2,john wall,202322,0.448513,874,15
128068,21400350,14-Dec-14,WAS vs. UTA,WAS,UTA,H,W,9,15,4,1:40,8.0,16,14.7,17.8,2,missed,"Burke, Trey",203504,4.0,0,0,john wall,202322,0.448513,874,15

In [49]:
Shotlog_1415['date'] = pd.to_datetime(Shotlog_1415['date'], errors = 'coerce')

C:\Users\nickc\AppData\Local\Temp\ipykernel_38460\3433117828.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  Shotlog_1415['date'] = pd.to_datetime(Shotlog_1415['date'], errors = 'coerce')

In [50]:
Shotlog_1415['shot_clock'].describe()

count    122502.000000
mean         12.453344
std           5.763265
min           0.000000
25%           8.200000
50%          12.300000
75%          16.675000
max          24.000000
Name: shot_clock, dtype: float64

In [51]:
Shotlog_1415[Shotlog_1415['shot_clock'].isna()]

,game_id,date,match,home_team,away_team,home_away,result,final_margin,shot_number,quarter,game_clock,shot_clock,dribbles,touch_time,shot_dist,points,current_shot_outcome,closest_defender,closest_defender_id,closest_def_dist,current_shot_hit,points_earned,shoot_player,player_id,average_hit,shot_count,shot_per_game
15,21400789,2015-02-11,ATL @ BOS,BOS,ATL,A,L,-1,6,1,0:01,NaN,2,2.5,24.6,3,missed,"Prince, Tayshaun",2419,7.8,0,0,al horford,201143,0.541259,715,15
52,21400602,2015-01-17,ATL @ CHI,CHI,ATL,A,W,8,12,3,0:03,NaN,0,1.0,20.5,2,missed,"Butler, Jimmy",202710,9.5,0,0,al horford,201143,0.541259,715,14
119,21400396,2014-12-20,ATL @ HOU,HOU,ATL,A,W,7,7,2,0:00,NaN,0,0.4,26.3,3,missed,"Harden, James",201935,8.2,0,0,al horford,201143,0.541259,715,10
182,21400449,2014-12-27,ATL @ MIL,MIL,ATL,A,W,5,1,1,10:16,NaN,0,0.8,8.2,2,missed,"O'Bryant, Johnny",203948,8.6,0,0,al horford,201143,0.541259,715,32
183,21400449,2014-12-27,ATL @ MIL,MIL,ATL,A,W,5,2,1,9:53,NaN,0,0.8,2.9,2,made,"O'Bryant, Johnny",203948,2.5,1,2,al horford,201143,0.541259,715,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127972,21400633,2015-01-21,WAS vs. OKC,WAS,OKC,H,L,-2,17,5,0:00,NaN,0,0.6,36.2,3,missed,"Westbrook, Russell",201566,6.2,0,0,john wall,202322,0.448513,874,17
128015,21400406,2014-12-21,WAS vs. PHX,WAS,PHX,H,L,-12,7,2,0:01,NaN,17,14.6,9.2,2,missed,"Morris, Markieff",202693,3.2,0,0,john wall,202322,0.448513,874,14
128020,21400406,2014-12-21,WAS vs. PHX,WAS,PHX,H,L,-12,12,3,0:02,NaN,9,9.9,19.8,2,missed,"Plumlee, Miles",203101,5.4,0,0,john wall,202322,0.448513,874,14
128044,21400707,2015-01-31,WAS vs. TOR,WAS,TOR,H,L,-4,7,2,0:03,NaN,18,17.3,18.5,2,missed,"Ross, Terrence",203082,6.5,0,0,john wall,202322,0.448513,874,16
128057,21400350,2014-12-14,WAS vs. UTA,WAS,UTA,H,W,9,4,1,0:02,NaN,0,0.0,6.3,3,missed,"Kanter, Enes",202683,3.9,0,0,john wall,202322,0.448513,874,15

In [52]:
# No of games

Shotlog_1415['game_id'].nunique()

904

In [53]:
# Shot Count

total_shots = Shotlog_1415.groupby('shoot_player')['shot_count'].mean()
no_total_shots = total_shots.sum()
no_total_shots

np.float64(128069.0)

In [54]:
Player_Stats

        shoot_player  average_hit
0       aaron brooks     0.415330
1       aaron gordon     0.528846
2    al farouq aminu     0.430233
3         al horford     0.541259
4       al jefferson     0.477500
..               ...          ...
276  wesley matthews     0.449198
277  wilson chandler     0.414734
278      zach lavine     0.423181
279    zach randolph     0.488823
280    zaza pachulia     0.431429

[281 rows x 2 columns]

In [55]:
# Create a lagged variable “lag_shot_hit” to indicate the result of the previous shot by the same player at the same game #

Shotlog_1415['lag_shot_hit']=Shotlog_1415.sort_values(by=['quarter','game_clock'], ascending=[True, False]).groupby(['shoot_player','game_id'])['current_shot_outcome'].shift(1)
Shotlog_1415.head()

,game_id,date,match,home_team,away_team,home_away,result,final_margin,shot_number,quarter,game_clock,shot_clock,dribbles,touch_time,shot_dist,points,current_shot_outcome,closest_defender,closest_defender_id,closest_def_dist,current_shot_hit,points_earned,shoot_player,player_id,average_hit,shot_count,shot_per_game,lag_shot_hit
0,21400280,2014-12-05,ATL @ BKN,BKN,ATL,A,W,23,1,1,11:23,5.6,0,1.2,19.6,2,made,"Lopez, Brook",201572,6.6,1,2,al horford,201143,0.541259,715,10,missed
1,21400280,2014-12-05,ATL @ BKN,BKN,ATL,A,W,23,2,1,10:48,5.6,0,1.1,14.5,2,missed,"Lopez, Brook",201572,5.6,0,0,al horford,201143,0.541259,715,10,made
2,21400280,2014-12-05,ATL @ BKN,BKN,ATL,A,W,23,3,1,9:40,11.0,0,0.4,5.8,2,missed,"Lopez, Brook",201572,4.7,0,0,al horford,201143,0.541259,715,10,NaN
3,21400280,2014-12-05,ATL @ BKN,BKN,ATL,A,W,23,4,1,7:09,13.5,0,0.8,20.8,2,missed,"Lopez, Brook",201572,5.8,0,0,al horford,201143,0.541259,715,10,missed
4,21400280,2014-12-05,ATL @ BKN,BKN,ATL,A,W,23,5,2,5:49,12.9,0,0.9,20.1,2,missed,"Lopez, Brook",201572,6.4,0,0,al horford,201143,0.541259,715,10,missed

In [56]:
Shot_log_1415 = Shotlog_1415.sort_values(by=['shoot_player', 'date', 'quarter', 'game_clock'], ascending = [True,True,True,False])

In [57]:
# Merge df with average stats

Shotlog_1415 = pd.merge(Shotlog_1415, Player_Stats, on=['shoot_player'])
Shotlog_1415

,game_id,date,match,home_team,away_team,home_away,result,final_margin,shot_number,quarter,game_clock,shot_clock,dribbles,touch_time,shot_dist,points,current_shot_outcome,closest_defender,closest_defender_id,closest_def_dist,current_shot_hit,points_earned,shoot_player,player_id,average_hit_x,shot_count,shot_per_game,lag_shot_hit,average_hit_y
0,21400280,2014-12-05,ATL @ BKN,BKN,ATL,A,W,23,1,1,11:23,5.6,0,1.2,19.6,2,made,"Lopez, Brook",201572,6.6,1,2,al horford,201143,0.541259,715,10,missed,0.541259
1,21400280,2014-12-05,ATL @ BKN,BKN,ATL,A,W,23,2,1,10:48,5.6,0,1.1,14.5,2,missed,"Lopez, Brook",201572,5.6,0,0,al horford,201143,0.541259,715,10,made,0.541259
2,21400280,2014-12-05,ATL @ BKN,BKN,ATL,A,W,23,3,1,9:40,11.0,0,0.4,5.8,2,missed,"Lopez, Brook",201572,4.7,0,0,al horford,201143,0.541259,715,10,NaN,0.541259
3,21400280,2014-12-05,ATL @ BKN,BKN,ATL,A,W,23,4,1,7:09,13.5,0,0.8,20.8,2,missed,"Lopez, Brook",201572,5.8,0,0,al horford,201143,0.541259,715,10,missed,0.541259
4,21400280,2014-12-05,ATL @ BKN,BKN,ATL,A,W,23,5,2,5:49,12.9,0,0.9,20.1,2,missed,"Lopez, Brook",201572,6.4,0,0,al horford,201143,0.541259,715,10,missed,0.541259
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128064,21400350,2014-12-14,WAS vs. UTA,WAS,UTA,H,W,9,11,3,2:59,21.1,3,4.0,1.7,2,made,"Burke, Trey",203504,4.7,1,2,john wall,202322,0.448513,874,15,missed,0.448513
128065,21400350,2014-12-14,WAS vs. UTA,WAS,UTA,H,W,9,12,3,0:43,6.1,2,2.2,17.8,2,made,"Exum, Dante",203957,3.4,1,2,john wall,202322,0.448513,874,15,missed,0.448513
128066,21400350,2014-12-14,WAS vs. UTA,WAS,UTA,H,W,9,13,4,2:18,4.3,0,0.0,3.2,2,missed,"Kanter, Enes",202683,1.2,0,0,john wall,202322,0.448513,874,15,made,0.448513
128067,21400350,2014-12-14,WAS vs. UTA,WAS,UTA,H,W,9,14,4,2:18,4.3,0,0.6,3.3,2,made,"Kanter, Enes",202683,1.4,1,2,john wall,202322,0.448513,874,15,missed,0.448513
128068,21400350,2014-12-14,WAS vs. UTA,WAS,UTA,H,W,9,15,4,1:40,8.0,16,14.7,17.8,2,missed,"Burke, Trey",203504,4.0,0,0,john wall,202322,0.448513,874,15,made,0.448513

In [58]:
Shot_log_1415 = Shotlog_1415.sort_values(by=['shoot_player', 'date', 'quarter', 'game_clock'], ascending = [True,True,True,False])
Shot_log_1415

,game_id,date,match,home_team,away_team,home_away,result,final_margin,shot_number,quarter,game_clock,shot_clock,dribbles,touch_time,shot_dist,points,current_shot_outcome,closest_defender,closest_defender_id,closest_def_dist,current_shot_hit,points_earned,shoot_player,player_id,average_hit_x,shot_count,shot_per_game,lag_shot_hit,average_hit_y
23705,21400010,2014-10-29,CHI @ NYK,NYK,CHI,A,W,24,1,1,1:12,14.4,11,8.9,5.7,2,made,"Prigioni, Pablo",203143,0.9,1,2,aaron brooks,201166,0.415330,561,5,NaN,0.415330
23706,21400010,2014-10-29,CHI @ NYK,NYK,CHI,A,W,24,2,1,0:45,16.3,0,1.1,25.1,3,made,"Smith, Jason",201160,8.0,1,3,aaron brooks,201166,0.415330,561,5,made,0.415330
23708,21400010,2014-10-29,CHI @ NYK,NYK,CHI,A,W,24,4,2,8:37,10.9,5,3.7,7.0,2,missed,"Smith, Jason",201160,3.0,0,0,aaron brooks,201166,0.415330,561,5,made,0.415330
23709,21400010,2014-10-29,CHI @ NYK,NYK,CHI,A,W,24,5,2,7:57,11.5,15,11.6,1.6,2,made,"Larkin, Shane",203499,5.2,1,2,aaron brooks,201166,0.415330,561,5,missed,0.415330
23707,21400010,2014-10-29,CHI @ NYK,NYK,CHI,A,W,24,3,2,10:23,18.1,5,4.3,6.7,2,made,"Acy, Quincy",203112,2.3,1,2,aaron brooks,201166,0.415330,561,5,made,0.415330
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74546,21400907,2015-03-04,MIL @ GSW,GSW,MIL,A,L,-9,5,2,5:19,5.2,2,3.8,5.0,2,missed,"Ezeli, Festus",203105,1.4,0,0,zaza pachulia,2585,0.431429,350,9,made,0.431429
74547,21400907,2015-03-04,MIL @ GSW,GSW,MIL,A,L,-9,6,2,5:17,24.0,0,0.3,3.8,2,missed,"Barnes, Harrison",203084,4.7,0,0,zaza pachulia,2585,0.431429,350,9,missed,0.431429
74548,21400907,2015-03-04,MIL @ GSW,GSW,MIL,A,L,-9,7,2,5:14,21.1,0,2.9,2.2,2,missed,"Barnes, Harrison",203084,1.2,0,0,zaza pachulia,2585,0.431429,350,9,missed,0.431429
74549,21400907,2015-03-04,MIL @ GSW,GSW,MIL,A,L,-9,8,2,4:17,9.8,0,0.6,10.2,2,made,"Livingston, Shaun",2733,2.7,1,2,zaza pachulia,2585,0.431429,350,9,missed,0.431429
74550,21400907,2015-03-04,MIL @ GSW,GSW,MIL,A,L,-9,9,3,11:08,10.6,1,1.0,8.7,2,made,"Curry, Stephen",201939,4.0,1,2,zaza pachulia,2585,0.431429,350,9,made,0.431429

In [59]:
Shotlog_1415 = Shotlog_1415[pd.notnull(Shotlog_1415['lag_shot_hit'])]

In [60]:
Shotlog_1415 = Shotlog_1415.rename(columns = {'average_hit_x': 'average_hit'})

In [61]:
Shotlog_1415 = Shotlog_1415.drop(columns = 'average_hit_y')

In [62]:
Shotlog_1415['lag_shot_hit'] = np.where(Shotlog_1415['lag_shot_hit'] == 'made', 1, 0)

In [63]:
Shotlog_1415.shape

(113726, 28)

## Part 2 - Conditional Probability and Autocorrelation

In [64]:
# Indicate where a player had a hit on consecutive shots

Shotlog_1415['cons_shot_hit'] = np.where(
    (Shotlog_1415['current_shot_hit'] == 1) & (Shotlog_1415['lag_shot_hit'] == 1),
    1,
    0
)

In [65]:
# Calculate Average cons_hit and Average lag_hit

player_prob = (
    Shotlog_1415
    .groupby('shoot_player')[['cons_shot_hit', 'lag_shot_hit']]
    .mean()
    .reset_index()
)

In [66]:
# Conditional Probability

player_prob['conditional_prob'] = player_prob['cons_shot_hit'] / player_prob['lag_shot_hit']
player_prob

        shoot_player  cons_shot_hit  lag_shot_hit  conditional_prob
0       aaron brooks       0.190000      0.420000          0.452381
1       aaron gordon       0.246753      0.545455          0.452381
2    al farouq aminu       0.181373      0.460784          0.393617
3         al horford       0.296353      0.534954          0.553977
4       al jefferson       0.216000      0.480000          0.450000
..               ...            ...           ...               ...
276  wesley matthews       0.194485      0.452830          0.429487
277  wilson chandler       0.161481      0.422222          0.382456
278      zach lavine       0.191223      0.432602          0.442029
279    zach randolph       0.241546      0.486312          0.496689
280    zaza pachulia       0.193980      0.431438          0.449612

[281 rows x 4 columns]

In [67]:
Player_Stats = pd.merge(player_prob, Player_Stats, on = ['shoot_player'])
Player_Stats

,shoot_player,cons_shot_hit,lag_shot_hit,conditional_prob,average_hit
0,aaron brooks,0.190000,0.420000,0.452381,0.415330
1,aaron gordon,0.246753,0.545455,0.452381,0.528846
2,al farouq aminu,0.181373,0.460784,0.393617,0.430233
3,al horford,0.296353,0.534954,0.553977,0.541259
4,al jefferson,0.216000,0.480000,0.450000,0.477500
...,...,...,...,...,...
276,wesley matthews,0.194485,0.452830,0.429487,0.449198
277,wilson chandler,0.161481,0.422222,0.382456,0.414734
278,zach lavine,0.191223,0.432602,0.442029,0.423181
279,zach randolph,0.241546,0.486312,0.496689,0.488823
280,zaza pachulia,0.193980,0.431438,0.449612,0.431429

In [68]:
Player_Stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 281 entries, 0 to 280
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   shoot_player      281 non-null    object
 1   cons_shot_hit     281 non-null    float64
 2   lag_shot_hit      281 non-null    float64
 3   conditional_prob  281 non-null    float64
 4   average_hit       281 non-null    float64
dtypes: float64(4), object(1)
memory usage: 11.1+ KB

In [69]:
# Drop Vals where average lag shot = 0

Player_Stats = Player_Stats[pd.notnull(Player_Stats['conditional_prob'])]

In [70]:
Player_Stats = Player_Stats.sort_values(by=['conditional_prob'], ascending=[False])
Player_Stats

,shoot_player,cons_shot_hit,lag_shot_hit,conditional_prob,average_hit
66,deandre jordan,0.504532,0.694864,0.726087,0.712468
270,tyson chandler,0.452632,0.663158,0.682540,0.676471
131,joey dorsey,0.351852,0.518519,0.678571,0.526882
98,greg smith,0.350000,0.550000,0.636364,0.617021
235,rudy gobert,0.387560,0.617225,0.627907,0.625468
...,...,...,...,...,...
183,marcus thornton,0.124542,0.402930,0.309091,0.411392
215,patrick beverley,0.117359,0.383863,0.305732,0.381579
155,kirk hinrich,0.101504,0.338346,0.300000,0.359873
62,dante exum,0.111111,0.382222,0.290698,0.343860
107,james ennis,0.111111,0.384615,0.288889,0.383648

In [71]:
# find the difference in probabilities for each player

Player_Stats['prob_dif'] = Player_Stats['conditional_prob'] - Player_Stats['average_hit']

In [72]:
# add shot count to df

player_shots = Shotlog_1415[['shoot_player', 'shot_count']]
Player_Stats = pd.merge(Player_Stats, player_shots, on=['shoot_player'])
Player_Stats = Player_Stats.sort_values(by=['prob_dif'], ascending = [False])
Player_Stats

,shoot_player,cons_shot_hit,lag_shot_hit,conditional_prob,average_hit,prob_dif,shot_count
623,joey dorsey,0.351852,0.518519,0.678571,0.526882,0.151690,93
631,joey dorsey,0.351852,0.518519,0.678571,0.526882,0.151690,93
630,joey dorsey,0.351852,0.518519,0.678571,0.526882,0.151690,93
629,joey dorsey,0.351852,0.518519,0.678571,0.526882,0.151690,93
628,joey dorsey,0.351852,0.518519,0.678571,0.526882,0.151690,93
...,...,...,...,...,...,...,...
112476,marcus thornton,0.124542,0.402930,0.309091,0.411392,-0.102301,316
112475,marcus thornton,0.124542,0.402930,0.309091,0.411392,-0.102301,316
112474,marcus thornton,0.124542,0.402930,0.309091,0.411392,-0.102301,316
112473,marcus thornton,0.124542,0.402930,0.309091,0.411392,-0.102301,316
112697,marcus thornton,0.124542,0.402930,0.309091,0.411392,-0.102301,316

In [73]:
Player_Stats

,shoot_player,cons_shot_hit,lag_shot_hit,conditional_prob,average_hit,prob_dif,shot_count
623,joey dorsey,0.351852,0.518519,0.678571,0.526882,0.151690,93
631,joey dorsey,0.351852,0.518519,0.678571,0.526882,0.151690,93
630,joey dorsey,0.351852,0.518519,0.678571,0.526882,0.151690,93
629,joey dorsey,0.351852,0.518519,0.678571,0.526882,0.151690,93
628,joey dorsey,0.351852,0.518519,0.678571,0.526882,0.151690,93
...,...,...,...,...,...,...,...
112476,marcus thornton,0.124542,0.402930,0.309091,0.411392,-0.102301,316
112475,marcus thornton,0.124542,0.402930,0.309091,0.411392,-0.102301,316
112474,marcus thornton,0.124542,0.402930,0.309091,0.411392,-0.102301,316
112473,marcus thornton,0.124542,0.402930,0.309091,0.411392,-0.102301,316
112697,marcus thornton,0.124542,0.402930,0.309091,0.411392,-0.102301,316

In [74]:
# t-test to test if the players’ probability of hit is statistically significantly different than their conditional probability

import scipy.stats as sp

sp.stats.ttest_ind(Player_Stats['conditional_prob'], Player_Stats['average_hit'])

C:\Users\nickc\AppData\Local\Temp\ipykernel_38460\1112064441.py:5: DeprecationWarning: Please import `ttest_ind` from the `scipy.stats` namespace; the `scipy.stats.stats` namespace is deprecated and will be removed in SciPy 2.0.0.
  sp.stats.ttest_ind(Player_Stats['conditional_prob'], Player_Stats['average_hit'])

TtestResult(statistic=np.float64(-42.570569041288444), pvalue=np.float64(0.0), df=np.float64(227450.0))

In [75]:
## Autocorrelation Coefficient
# Calculate the autocorrelation coefficient “current_shot_hit” variable and the “lag_shot_hit” variable. 

Shotlog_1415['current_shot_hit'].corr(Shotlog_1415['lag_shot_hit'])

np.float64(-0.008142259125215375)

In [76]:
# Calculate coefficient for each player

player_coef = Shotlog_1415.groupby('shoot_player')[['current_shot_hit', 'lag_shot_hit']].corr().unstack().iloc[:,1].reset_index()
player_coef.columns = player_coef.columns.get_level_values(0)
player_coef = player_coef.rename(columns = {'current_shot_hit':'autocor'})
player_coef

        shoot_player   autocor
0       aaron brooks  0.059317
1       aaron gordon -0.147119
2    al farouq aminu -0.052326
3         al horford  0.031123
4       al jefferson -0.062808
..               ...       ...
276  wesley matthews -0.024146
277  wilson chandler -0.053602
278      zach lavine  0.022159
279    zach randolph  0.017064
280    zaza pachulia  0.026059

[281 rows x 2 columns]

In [77]:
avg_player_shots = Shotlog_1415[['shoot_player', 'shot_per_game']]
avg_player_shots = avg_player_shots.groupby(['shoot_player'])['shot_per_game'].mean().reset_index(name='avg_shot_game')
avg_player_shots

        shoot_player  avg_shot_game
0       aaron brooks      14.504000
1       aaron gordon       6.168831
2    al farouq aminu       7.691176
3         al horford      18.129179
4       al jefferson      21.064000
..               ...            ...
276  wesley matthews      16.798258
277  wilson chandler      17.503704
278      zach lavine      11.021944
279    zach randolph      18.230274
280    zaza pachulia       9.976589

[281 rows x 2 columns]

In [78]:
player_coef = pd.merge(player_coef, avg_player_shots, on = 'shoot_player').sort_values(by=['autocor'], ascending=[False])
player_coef

         shoot_player   autocor  avg_shot_game
131       joey dorsey  0.294564       4.333333
267  tyler hansbrough  0.159668       5.155172
195       mike miller  0.114286       6.483871
7            alex len  0.109967       9.016598
121        jeremy lin  0.098634      13.407895
..                ...       ...            ...
21        aron baynes -0.156532       8.708738
73   derrick williams -0.162994       9.966667
183   marcus thornton -0.163065       9.937729
107       james ennis -0.181935       7.555556
9          alonzo gee -0.229413       6.950980

[281 rows x 3 columns]

## Part 3 - Regression Analyses

In [79]:
# prediction error : dif betwen outcome and average success rate

Shotlog_1415['error'] = Shotlog_1415['current_shot_hit'] - Shotlog_1415['average_hit']
Shotlog_1415['lag_error'] = Shotlog_1415['lag_shot_hit'] - Shotlog_1415['average_hit']

In [80]:
Shotlog_1415['error'].describe()

count    113726.000000
mean          0.000139
std           0.494977
min          -0.712468
25%          -0.449198
50%          -0.385084
75%           0.539597
max           0.691489
Name: error, dtype: float64

In [81]:
Shotlog_1415['lag_error'].describe()

count    113726.000000
mean          0.004404
std           0.495804
min          -0.712468
25%          -0.449198
50%          -0.383648
75%           0.541485
max           0.691489
Name: lag_error, dtype: float64

In [82]:
# linear regression controlling for variables

import statsmodels.api as sm
import statsmodels.formula.api as smf

reg_1 = smf.ols(
    formula='error ~ lag_error + shot_dist + dribbles + touch_time + C(points) + C(quarter) + home_away + closest_def_dist + C(shoot_player) + C(closest_defender)',
    data=Shotlog_1415
).fit()

print(reg_1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  error   R-squared:                       0.058
Model:                            OLS   Adj. R-squared:                  0.051
Method:                 Least Squares   F-statistic:                     9.053
Date:                Wed, 03 Dec 2025   Prob (F-statistic):               0.00
Time:                        23:00:36   Log-Likelihood:                -78009.
No. Observations:              113726   AIC:                         1.576e+05
Df Residuals:                  112960   BIC:                         1.649e+05
Df Model:                         765
Covariance Type:            nonrobust
====================================================================================================================
                                                       coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------------------
Intercept                                            0.1641      0.038      4.299      0.000       0.089       0.239
C(points)[T.3]                                       0.0367      0.005      6.970      0.000       0.026       0.047
C(quarter)[T.2]                                     -0.0082      0.004     -1.873      0.061      -0.017       0.000
C(quarter)[T.3]                                      0.0015      0.004      0.360      0.719      -0.007       0.010
C(quarter)[T.4]                                     -0.0077      0.004     -1.728      0.084      -0.016       0.001
C(quarter)[T.5]                                     -0.0407      0.016     -2.480      0.013      -0.073      -0.009
C(quarter)[T.6]                                      0.0108      0.038      0.288      0.773      -0.063       0.084
C(quarter)[T.7]                                     -0.0168      0.074     -0.226      0.821      -0.162       0.128
home_away[T.H]                                       0.0079      0.003      2.728      0.006       0.002       0.014
C(shoot_player)[T.aaron gordon]                     -0.1124      0.059     -1.895      0.058      -0.229       0.004
C(shoot_player)[T.al farouq aminu]                  -0.0931      0.040     -2.308      0.021      -0.172      -0.014
C(shoot_player)[T.al horford]                       -0.0635      0.029     -2.190      0.029      -0.120      -0.007
C(shoot_player)[T.al jefferson]                     -0.0354      0.028     -1.250      0.211      -0.091       0.020
C(shoot_player)[T.alan anderson]                    -0.0233      0.036     -0.643      0.520      -0.094       0.048
C(shoot_player)[T.alan crabbe]                      -0.0676      0.065     -1.042      0.297      -0.195       0.060
C(shoot_player)[T.alex len]                         -0.1278      0.038     -3.352      0.001      -0.203      -0.053
C(shoot_player)[T.alexis ajinca]                    -0.0930      0.044     -2.138      0.033      -0.178      -0.008
C(shoot_player)[T.alonzo gee]                       -0.0638      0.053     -1.208      0.227      -0.167       0.040
C(shoot_player)[T.amare stoudemire]                 -0.0973      0.036     -2.722      0.006      -0.167      -0.027
C(shoot_player)[T.amir johnson]                     -0.1114      0.034     -3.269      0.001      -0.178      -0.045
C(shoot_player)[T.andre drummond]                   -0.1294      0.030     -4.385      0.000      -0.187      -0.072
C(shoot_player)[T.andre iguodala]                   -0.0428      0.036     -1.190      0.234      -0.113       0.028
C(shoot_player)[T.andre miller]                     -0.0618      0.049     -1.266      0.206      -0.157       0.034
C(shoot_player)[T.andre roberson]                   -0.1556      0.049     -3.190      0.001      -0.251      -0.060
C(shoot_player)[T.andrew bogut]                     -0.1309      0.041     -3.191      0.001      -0.211      -0.051
C(shoot_player)[T.andrew wiggins]                   -0.0363      0.028     -1.284      0.199      -0.092       0.019
C(shoot_player)[T.anthony bennett]                  -0.0366      0.039     -0.937      0.349      -0.113       0.040
C(shoot_player)[T.anthony davis]                    -0.0587      0.028     -2.099      0.036      -0.113      -0.004
C(shoot_player)[T.anthony morrow]                   -0.0090      0.034     -0.267      0.789      -0.075       0.057
C(shoot_player)[T.aron baynes]                      -0.1333      0.040     -3.303      0.001      -0.212      -0.054
C(shoot_player)[T.arron afflalo]                    -0.0092      0.029     -0.316      0.752      -0.066       0.048
C(shoot_player)[T.avery bradley]                    -0.0008      0.029     -0.028      0.977      -0.057       0.055
C(shoot_player)[T.ben gordon]                        0.0275      0.040      0.686      0.493      -0.051       0.106
C(shoot_player)[T.ben mclemore]                     -0.0105      0.030     -0.346      0.729      -0.070       0.049
C(shoot_player)[T.beno urdih]                       -0.0461      0.035     -1.301      0.193      -0.116       0.023
C(shoot_player)[T.bismack biyombo]                  -0.1133      0.058     -1.962      0.050      -0.226      -0.000
C(shoot_player)[T.blake griffin]                    -0.0650      0.028     -2.352      0.019      -0.119      -0.011
C(shoot_player)[T.bojan bogdanovic]                 -0.0383      0.035     -1.087      0.277      -0.107       0.031
C(shoot_player)[T.boris diaw]                       -0.0717      0.033     -2.162      0.031      -0.137      -0.007
C(shoot_player)[T.bradley beal]                     -0.0202      0.030     -0.669      0.503      -0.079       0.039
C(shoot_player)[T.brandon bass]                     -0.0503      0.032     -1.559      0.119      -0.113       0.013
C(shoot_player)[T.brandon jennings]                 -0.0048      0.031     -0.158      0.875      -0.065       0.055
C(shoot_player)[T.brandon knight]                   -0.0128      0.028     -0.459      0.646      -0.067       0.042
C(shoot_player)[T.brian roberts]                     0.0095      0.035      0.271      0.786      -0.059       0.078
C(shoot_player)[T.brook lopez]                      -0.0608      0.030     -2.039      0.041      -0.119      -0.002
C(shoot_player)[T.carl landry]                      -0.0804      0.038     -2.094      0.036      -0.156      -0.005
C(shoot_player)[T.carlos boozer]                    -0.0451      0.030     -1.503      0.133      -0.104       0.014
C(shoot_player)[T.carmelo anthony]                   0.0034      0.028      0.121      0.904      -0.052       0.059
C(shoot_player)[T.caron butler]                      0.0421      0.038      1.095      0.273      -0.033       0.117
C(shoot_player)[T.chandler parsons]                 -0.0460      0.029     -1.571      0.116      -0.103       0.011
C(shoot_player)[T.channing frye]                     0.0536      0.034      1.583      0.113      -0.013       0.120
C(shoot_player)[T.charlie villanueva]                0.0358      0.041      0.877      0.380      -0.044       0.116
C(shoot_player)[T.chase budinger]                    0.0002      0.045      0.004      0.997      -0.087       0.088
C(shoot_player)[T.chris andersen]                   -0.1687      0.054     -3.149      0.002      -0.274      -0.064
C(shoot_player)[T.chris bosh]                        0.0073      0.029      0.256      0.798      -0.049       0.063
C(shoot_player)[T.chris copeland]                    0.0063      0.037      0.172      0.864      -0.066       0.079
C(shoot_player)[T.chris kaman]                      -0.0638      0.033     -1.916      0.055      -0.129       0.001
C(shoot_player)[T.chris paul]                        0.0103      0.028      0.372      0.710      -0.044       0.064
C(shoot_player)[T.cj mccollum]                       0.0142      0.047      0.304      0.761      -0.077       0.106
C(shoot_player)[T.cj miles]                          0.0250      0.031      0.815      0.415      -0.035       0.085
C(shoot_player)[T.cj watson]                         0.0123      0.037      0.333      0.739      -0.060       0.085
C(shoot_player)[T.cody zeller]                      -0.0956      0.036     -2.684      0.007      -0.165      -0.026
C(shoot_player)[T.cole aldrich]                     -0.1078      0.045     -2.401      0.016      -0.196      -0.020
C(shoot_player)[T.cory joseph]                      -0.0970      0.036     -2.707      0.007      -0.167      -0.027
C(shoot_player)[T.courtney lee]                     -0.0275      0.032     -0.855      0.393      -0.091       0.036
C(shoot_player)[T.damian lillard]                    0.0026      0.027      0.096      0.924      -0.050       0.055
C(shoot_player)[T.damjan rudez]                      0.0306      0.046      0.670      0.503      -0.059       0.120
C(shoot_player)[T.danilo gallinai]                   0.0349      0.035      0.990      0.322      -0.034       0.104
C(shoot_player)[T.danny green]                      -0.0085      0.031     -0.277      0.782      -0.069       0.052
C(shoot_player)[T.dante cunningham]                 -0.0574      0.041     -1.416      0.157      -0.137       0.022
C(shoot_player)[T.dante exum]                       -0.0264      0.039     -0.678      0.498      -0.103       0.050
C(shoot_player)[T.darrell arthur]                   -0.0366      0.036     -1.030      0.303      -0.106       0.033
C(shoot_player)[T.darren collison]                  -0.0307      0.031     -1.001      0.317      -0.091       0.029
C(shoot_player)[T.david west]                       -0.0215      0.031     -0.686      0.493      -0.083       0.040
C(shoot_player)[T.deandre jordan]                   -0.1555      0.035     -4.505      0.000      -0.223      -0.088
C(shoot_player)[T.demarcus cousins]                 -0.0702      0.028     -2.481      0.013      -0.126      -0.015
C(shoot_player)[T.demarre carroll]                  -0.0594      0.032     -1.835      0.067      -0.123       0.004
C(shoot_player)[T.dennis schroder]                  -0.0576      0.033     -1.766      0.077      -0.122       0.006
C(shoot_player)[T.deron williams]                    0.0014      0.031      0.046      0.963      -0.060       0.063
C(shoot_player)[T.derrick favors]                   -0.0804      0.029     -2.740      0.006      -0.138      -0.023
C(shoot_player)[T.derrick rose]                     -0.0107      0.028     -0.381      0.703      -0.066       0.045
C(shoot_player)[T.derrick williams]                 -0.0729      0.038     -1.912      0.056      -0.148       0.002
C(shoot_player)[T.devin harris]                     -0.0272      0.033     -0.817      0.414      -0.092       0.038
C(shoot_player)[T.dirk nowtizski]                    0.0223      0.028      0.793      0.428      -0.033       0.077
C(shoot_player)[T.dj augustin]                      -0.0163      0.031     -0.521      0.602      -0.077       0.045
C(shoot_player)[T.donald sloan]                     -0.0079      0.035     -0.222      0.824      -0.077       0.062
C(shoot_player)[T.donatas motiejunas]               -0.0860      0.031     -2.815      0.005      -0.146      -0.026
C(shoot_player)[T.draymond green]                   -0.0454      0.031     -1.469      0.142      -0.106       0.015
C(shoot_player)[T.dwayne wade]                      -0.0255      0.029     -0.884      0.377      -0.082       0.031
C(shoot_player)[T.dwight howard]                    -0.1278      0.036     -3.596      0.000      -0.197      -0.058
C(shoot_player)[T.ed davis]                         -0.1313      0.036     -3.656      0.000      -0.202      -0.061
C(shoot_player)[T.elfrid payton]                    -0.0909      0.032     -2.825      0.005      -0.154      -0.028
C(shoot_player)[T.enes kanter]                      -0.0918      0.030     -3.085      0.002      -0.150      -0.033
C(shoot_player)[T.eric bledsoe]                     -0.0536      0.028     -1.894      0.058      -0.109       0.002
C(shoot_player)[T.evan fournier]                    -0.0477      0.031     -1.554      0.120      -0.108       0.012
C(shoot_player)[T.evan turner]                      -0.0462      0.032     -1.454      0.146      -0.108       0.016
C(shoot_player)[T.garrett temple]                   -0.0244      0.049     -0.502      0.615      -0.119       0.071
C(shoot_player)[T.gary neal]                         0.0095      0.032      0.294      0.769      -0.054       0.073
C(shoot_player)[T.gerald green]                      0.0245      0.030      0.821      0.411      -0.034       0.083
C(shoot_player)[T.gerald henderson]                 -0.0196      0.031     -0.638      0.523      -0.080       0.041
C(shoot_player)[T.giannis antetokounmpo]            -0.0802      0.031     -2.590      0.010      -0.141      -0.020
C(shoot_player)[T.glen davis]                       -0.1334      0.048     -2.768      0.006      -0.228      -0.039
C(shoot_player)[T.goran dragic]                     -0.0734      0.029     -2.576      0.010      -0.129      -0.018
C(shoot_player)[T.gordon hayward]                   -0.0345      0.028     -1.245      0.213      -0.089       0.020
C(shoot_player)[T.gorgui dieng]                     -0.0939      0.034     -2.762      0.006      -0.161      -0.027
C(shoot_player)[T.greg monroe]                      -0.1095      0.029     -3.772      0.000      -0.166      -0.053
C(shoot_player)[T.greg smith]                       -0.1385      0.110     -1.255      0.209      -0.355       0.078
C(shoot_player)[T.greivis vasquez]                   0.0006      0.031      0.019      0.985      -0.060       0.061
C(shoot_player)[T.harrison barnes]                  -0.0715      0.033     -2.201      0.028      -0.135      -0.008
C(shoot_player)[T.hedo turkoglu]                     0.0500      0.062      0.804      0.422      -0.072       0.172
C(shoot_player)[T.henry sims]                       -0.0538      0.034     -1.601      0.109      -0.120       0.012
C(shoot_player)[T.hollis thompson]                  -0.0175      0.036     -0.492      0.623      -0.088       0.052
C(shoot_player)[T.isaiah thomas]                    -0.0152      0.030     -0.510      0.610      -0.074       0.043
C(shoot_player)[T.jakarr sampson]                   -0.0894      0.044     -2.041      0.041      -0.175      -0.004
C(shoot_player)[T.jamal crawford]                    0.0479      0.028      1.701      0.089      -0.007       0.103
C(shoot_player)[T.james ennis]                      -0.0461      0.050     -0.926      0.355      -0.144       0.051
C(shoot_player)[T.james harden]                      0.0055      0.027      0.208      0.835      -0.047       0.058
C(shoot_player)[T.james johnson]                    -0.1212      0.037     -3.274      0.001      -0.194      -0.049
C(shoot_player)[T.jared dudley]                     -0.0247      0.035     -0.698      0.485      -0.094       0.045
C(shoot_player)[T.jared sullinger]                  -0.0244      0.029     -0.831      0.406      -0.082       0.033
C(shoot_player)[T.jarrett jack]                     -0.0214      0.030     -0.715      0.474      -0.080       0.037
C(shoot_player)[T.jason maxiell]                    -0.0836      0.055     -1.512      0.130      -0.192       0.025
C(shoot_player)[T.jason smith]                      -0.0216      0.033     -0.648      0.517      -0.087       0.044
C(shoot_player)[T.jason terry]                       0.0190      0.036      0.526      0.599      -0.052       0.090
C(shoot_player)[T.jason thompson]                   -0.1176      0.039     -3.052      0.002      -0.193      -0.042
C(shoot_player)[T.jeff green]                       -0.0243      0.029     -0.839      0.401      -0.081       0.032
C(shoot_player)[T.jeff teague]                      -0.0701      0.029     -2.413      0.016      -0.127      -0.013
C(shoot_player)[T.jerami grant]                     -0.0257      0.043     -0.602      0.547      -0.109       0.058
C(shoot_player)[T.jeremy lamb]                       0.0114      0.042      0.273      0.785      -0.070       0.093
C(shoot_player)[T.jeremy lin]                       -0.0089      0.031     -0.283      0.777      -0.070       0.053
C(shoot_player)[T.jerome jordan]                    -0.1128      0.067     -1.688      0.091      -0.244       0.018
C(shoot_player)[T.jerryd bayless]                   -0.0057      0.034     -0.169      0.866      -0.072       0.061
C(shoot_player)[T.jimmer dredette]                  -0.0588      0.050     -1.169      0.243      -0.158       0.040
C(shoot_player)[T.jimmy butler]                     -0.0468      0.028     -1.652      0.098      -0.102       0.009
C(shoot_player)[T.jj hickson]                       -0.1292      0.036     -3.562      0.000      -0.200      -0.058
C(shoot_player)[T.jj redick]                         0.0032      0.030      0.109      0.913      -0.055       0.061
C(shoot_player)[T.joakim noah]                      -0.1125      0.036     -3.134      0.002      -0.183      -0.042
C(shoot_player)[T.joe harris]                       -0.0115      0.064     -0.180      0.857      -0.137       0.114
C(shoot_player)[T.joe johnson]                      -0.0051      0.028     -0.180      0.857      -0.061       0.051
C(shoot_player)[T.joey dorsey]                      -0.1520      0.069     -2.189      0.029      -0.288      -0.016
C(shoot_player)[T.john henson]                      -0.1467      0.041     -3.583      0.000      -0.227      -0.066
C(shoot_player)[T.john wall]                        -0.0195      0.028     -0.706      0.480      -0.074       0.035
C(shoot_player)[T.jon ingles]                        0.0022      0.043      0.050      0.960      -0.083       0.087
C(shoot_player)[T.jon leuer]                        -0.0931      0.040     -2.309      0.021      -0.172      -0.014
C(shoot_player)[T.jonas jerebko]                    -0.0669      0.042     -1.590      0.112      -0.149       0.016
C(shoot_player)[T.jonas valanciunas]                -0.1157      0.032     -3.597      0.000      -0.179      -0.053
C(shoot_player)[T.jordan farmar]                     0.0513      0.049      1.049      0.294      -0.045       0.147
C(shoot_player)[T.jordan hill]                      -0.0402      0.030     -1.336      0.181      -0.099       0.019
C(shoot_player)[T.jose calderon]                     0.0283      0.035      0.803      0.422      -0.041       0.097
C(shoot_player)[T.jose juan barea]                  -0.0394      0.033     -1.179      0.238      -0.105       0.026
C(shoot_player)[T.jrue holiday]                     -0.0387      0.031     -1.242      0.214      -0.100       0.022
C(shoot_player)[T.jusuf nurkic]                     -0.1158      0.038     -3.062      0.002      -0.190      -0.042
C(shoot_player)[T.kawhi leonard]                    -0.0356      0.031     -1.142      0.253      -0.097       0.026
C(shoot_player)[T.kelly olynyk]                     -0.0620      0.036     -1.747      0.081      -0.132       0.008
C(shoot_player)[T.kemba walker]                     -0.0100      0.029     -0.346      0.729      -0.066       0.047
C(shoot_player)[T.kendrick perkins]                 -0.1470      0.046     -3.191      0.001      -0.237      -0.057
C(shoot_player)[T.kenneth faried]                   -0.1084      0.032     -3.434      0.001      -0.170      -0.047
C(shoot_player)[T.kent bazemore]                    -0.0522      0.044     -1.176      0.239      -0.139       0.035
C(shoot_player)[T.kentavious caldwell-pope]         -0.0142      0.029     -0.486      0.627      -0.071       0.043
C(shoot_player)[T.kevin garnett]                    -0.0587      0.037     -1.565      0.117      -0.132       0.015
C(shoot_player)[T.kevin love]                       -0.0228      0.028     -0.800      0.424      -0.079       0.033

In [83]:
# Weighted Least Squares Regression by no shots/game

reg_2 = smf.wls(
    formula='error ~ lag_error + shot_dist + dribbles + touch_time + C(points) + C(quarter) + home_away + closest_def_dist + C(shoot_player) + C(closest_defender)',
    data=Shotlog_1415,
    weights=1/Shotlog_1415['shot_per_game']
).fit()

print(reg_2.summary())

                            WLS Regression Results
==============================================================================
Dep. Variable:                  error   R-squared:                       0.062
Model:                            WLS   Adj. R-squared:                  0.056
Method:                 Least Squares   F-statistic:                     9.745
Date:                Wed, 03 Dec 2025   Prob (F-statistic):               0.00
Time:                        23:00:47   Log-Likelihood:                -86929.
No. Observations:              113726   AIC:                         1.754e+05
Df Residuals:                  112960   BIC:                         1.828e+05
Df Model:                         765
Covariance Type:            nonrobust
====================================================================================================================
                                                       coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------------------
Intercept                                            0.1926      0.036      5.335      0.000       0.122       0.263
C(points)[T.3]                                       0.0439      0.005      8.302      0.000       0.034       0.054
C(quarter)[T.2]                                     -0.0048      0.004     -1.078      0.281      -0.014       0.004
C(quarter)[T.3]                                      0.0047      0.004      1.079      0.281      -0.004       0.013
C(quarter)[T.4]                                      0.0002      0.005      0.043      0.966      -0.009       0.009
C(quarter)[T.5]                                     -0.0152      0.019     -0.792      0.428      -0.053       0.022
C(quarter)[T.6]                                      0.0337      0.045      0.754      0.451      -0.054       0.121
C(quarter)[T.7]                                     -0.0630      0.087     -0.722      0.471      -0.234       0.108
home_away[T.H]                                       0.0073      0.003      2.550      0.011       0.002       0.013
C(shoot_player)[T.aaron gordon]                     -0.1259      0.043     -2.933      0.003      -0.210      -0.042
C(shoot_player)[T.al farouq aminu]                  -0.1310      0.033     -3.982      0.000      -0.196      -0.067
C(shoot_player)[T.al horford]                       -0.0602      0.031     -1.968      0.049      -0.120      -0.000
C(shoot_player)[T.al jefferson]                     -0.0442      0.031     -1.421      0.155      -0.105       0.017
C(shoot_player)[T.alan anderson]                    -0.0624      0.032     -1.978      0.048      -0.124      -0.001
C(shoot_player)[T.alan crabbe]                      -0.0605      0.043     -1.405      0.160      -0.145       0.024
C(shoot_player)[T.alex len]                         -0.1157      0.032     -3.600      0.000      -0.179      -0.053
C(shoot_player)[T.alexis ajinca]                    -0.0805      0.036     -2.228      0.026      -0.151      -0.010
C(shoot_player)[T.alonzo gee]                       -0.0492      0.039     -1.275      0.202      -0.125       0.026
C(shoot_player)[T.amare stoudemire]                 -0.1133      0.034     -3.374      0.001      -0.179      -0.048
C(shoot_player)[T.amir johnson]                     -0.1039      0.032     -3.253      0.001      -0.166      -0.041
C(shoot_player)[T.andre drummond]                   -0.1500      0.031     -4.912      0.000      -0.210      -0.090
C(shoot_player)[T.andre iguodala]                   -0.0518      0.031     -1.650      0.099      -0.113       0.010
C(shoot_player)[T.andre miller]                     -0.0840      0.036     -2.354      0.019      -0.154      -0.014
C(shoot_player)[T.andre roberson]                   -0.1516      0.038     -4.011      0.000      -0.226      -0.078
C(shoot_player)[T.andrew bogut]                     -0.1282      0.034     -3.787      0.000      -0.195      -0.062
C(shoot_player)[T.andrew wiggins]                   -0.0612      0.030     -2.039      0.041      -0.120      -0.002
C(shoot_player)[T.anthony bennett]                  -0.0638      0.034     -1.888      0.059      -0.130       0.002
C(shoot_player)[T.anthony davis]                    -0.0781      0.031     -2.514      0.012      -0.139      -0.017
C(shoot_player)[T.anthony morrow]                   -0.0112      0.032     -0.354      0.723      -0.074       0.051
C(shoot_player)[T.aron baynes]                      -0.1314      0.034     -3.835      0.000      -0.199      -0.064
C(shoot_player)[T.arron afflalo]                    -0.0078      0.030     -0.260      0.795      -0.066       0.051
C(shoot_player)[T.avery bradley]                    -0.0097      0.030     -0.325      0.745      -0.068       0.049
C(shoot_player)[T.ben gordon]                       -0.0151      0.034     -0.447      0.655      -0.081       0.051
C(shoot_player)[T.ben mclemore]                     -0.0159      0.031     -0.515      0.607      -0.076       0.045
C(shoot_player)[T.beno urdih]                       -0.0633      0.032     -2.002      0.045      -0.125      -0.001
C(shoot_player)[T.bismack biyombo]                  -0.1054      0.041     -2.594      0.009      -0.185      -0.026
C(shoot_player)[T.blake griffin]                    -0.0670      0.030     -2.200      0.028      -0.127      -0.007
C(shoot_player)[T.bojan bogdanovic]                 -0.0698      0.032     -2.171      0.030      -0.133      -0.007
C(shoot_player)[T.boris diaw]                       -0.0855      0.032     -2.699      0.007      -0.148      -0.023
C(shoot_player)[T.bradley beal]                     -0.0289      0.032     -0.906      0.365      -0.091       0.034
C(shoot_player)[T.brandon bass]                     -0.0461      0.031     -1.499      0.134      -0.106       0.014
C(shoot_player)[T.brandon jennings]                 -0.0378      0.033     -1.159      0.247      -0.102       0.026
C(shoot_player)[T.brandon knight]                   -0.0272      0.030     -0.918      0.359      -0.085       0.031
C(shoot_player)[T.brian roberts]                    -0.0110      0.031     -0.352      0.724      -0.072       0.050
C(shoot_player)[T.brook lopez]                      -0.0821      0.031     -2.665      0.008      -0.142      -0.022
C(shoot_player)[T.carl landry]                      -0.1033      0.034     -3.046      0.002      -0.170      -0.037
C(shoot_player)[T.carlos boozer]                    -0.0572      0.031     -1.857      0.063      -0.118       0.003
C(shoot_player)[T.carmelo anthony]                   0.0156      0.033      0.477      0.633      -0.048       0.079
C(shoot_player)[T.caron butler]                      0.0381      0.033      1.160      0.246      -0.026       0.102
C(shoot_player)[T.chandler parsons]                 -0.0527      0.031     -1.722      0.085      -0.113       0.007
C(shoot_player)[T.channing frye]                     0.0522      0.031      1.677      0.093      -0.009       0.113
C(shoot_player)[T.charlie villanueva]                0.0235      0.036      0.657      0.511      -0.046       0.093
C(shoot_player)[T.chase budinger]                   -0.0152      0.035     -0.428      0.668      -0.085       0.054
C(shoot_player)[T.chris andersen]                   -0.1747      0.040     -4.402      0.000      -0.253      -0.097
C(shoot_player)[T.chris bosh]                        0.0131      0.032      0.415      0.678      -0.049       0.075
C(shoot_player)[T.chris copeland]                   -0.0231      0.034     -0.675      0.500      -0.090       0.044
C(shoot_player)[T.chris kaman]                      -0.0882      0.031     -2.833      0.005      -0.149      -0.027
C(shoot_player)[T.chris paul]                        0.0055      0.030      0.187      0.851      -0.052       0.063
C(shoot_player)[T.cj mccollum]                      -0.0083      0.037     -0.223      0.824      -0.082       0.065
C(shoot_player)[T.cj miles]                         -0.0005      0.032     -0.015      0.988      -0.063       0.062
C(shoot_player)[T.cj watson]                         0.0157      0.033      0.469      0.639      -0.050       0.081
C(shoot_player)[T.cody zeller]                      -0.1264      0.031     -4.022      0.000      -0.188      -0.065
C(shoot_player)[T.cole aldrich]                     -0.0759      0.036     -2.084      0.037      -0.147      -0.005
C(shoot_player)[T.cory joseph]                      -0.1127      0.033     -3.425      0.001      -0.177      -0.048
C(shoot_player)[T.courtney lee]                     -0.0437      0.031     -1.390      0.165      -0.105       0.018
C(shoot_player)[T.damian lillard]                   -0.0008      0.030     -0.027      0.978      -0.059       0.058
C(shoot_player)[T.damjan rudez]                      0.0320      0.035      0.903      0.367      -0.037       0.101
C(shoot_player)[T.danilo gallinai]                   0.0008      0.034      0.025      0.980      -0.065       0.066
C(shoot_player)[T.danny green]                      -0.0185      0.031     -0.595      0.552      -0.080       0.043
C(shoot_player)[T.dante cunningham]                 -0.0779      0.034     -2.300      0.021      -0.144      -0.012
C(shoot_player)[T.dante exum]                       -0.0560      0.032     -1.763      0.078      -0.118       0.006
C(shoot_player)[T.darrell arthur]                   -0.0401      0.032     -1.236      0.217      -0.104       0.024
C(shoot_player)[T.darren collison]                  -0.0348      0.032     -1.084      0.279      -0.098       0.028
C(shoot_player)[T.david west]                       -0.0129      0.032     -0.401      0.689      -0.076       0.050
C(shoot_player)[T.deandre jordan]                   -0.1444      0.031     -4.714      0.000      -0.204      -0.084
C(shoot_player)[T.demarcus cousins]                 -0.0763      0.032     -2.381      0.017      -0.139      -0.013
C(shoot_player)[T.demarre carroll]                  -0.0510      0.031     -1.618      0.106      -0.113       0.011
C(shoot_player)[T.dennis schroder]                  -0.0454      0.031     -1.469      0.142      -0.106       0.015
C(shoot_player)[T.deron williams]                   -0.0189      0.032     -0.587      0.557      -0.082       0.044
C(shoot_player)[T.derrick favors]                   -0.0886      0.031     -2.896      0.004      -0.149      -0.029
C(shoot_player)[T.derrick rose]                     -0.0217      0.031     -0.693      0.489      -0.083       0.040
C(shoot_player)[T.derrick williams]                 -0.0822      0.034     -2.421      0.015      -0.149      -0.016
C(shoot_player)[T.devin harris]                     -0.0403      0.030     -1.322      0.186      -0.100       0.019
C(shoot_player)[T.dirk nowtizski]                    0.0274      0.030      0.914      0.360      -0.031       0.086
C(shoot_player)[T.dj augustin]                      -0.0330      0.030     -1.089      0.276      -0.092       0.026
C(shoot_player)[T.donald sloan]                     -0.0039      0.034     -0.116      0.907      -0.070       0.062
C(shoot_player)[T.donatas motiejunas]               -0.0981      0.031     -3.205      0.001      -0.158      -0.038
C(shoot_player)[T.draymond green]                   -0.0631      0.031     -2.055      0.040      -0.123      -0.003
C(shoot_player)[T.dwayne wade]                      -0.0213      0.033     -0.652      0.514      -0.085       0.043
C(shoot_player)[T.dwight howard]                    -0.1313      0.035     -3.722      0.000      -0.200      -0.062
C(shoot_player)[T.ed davis]                         -0.1422      0.032     -4.462      0.000      -0.205      -0.080
C(shoot_player)[T.elfrid payton]                    -0.0942      0.031     -3.077      0.002      -0.154      -0.034
C(shoot_player)[T.enes kanter]                      -0.0899      0.030     -2.963      0.003      -0.149      -0.030
C(shoot_player)[T.eric bledsoe]                     -0.0485      0.030     -1.629      0.103      -0.107       0.010
C(shoot_player)[T.evan fournier]                    -0.0568      0.031     -1.839      0.066      -0.117       0.004
C(shoot_player)[T.evan turner]                      -0.0593      0.030     -1.951      0.051      -0.119       0.000
C(shoot_player)[T.garrett temple]                   -0.0320      0.039     -0.813      0.416      -0.109       0.045
C(shoot_player)[T.gary neal]                         0.0050      0.032      0.157      0.875      -0.057       0.067
C(shoot_player)[T.gerald green]                      0.0122      0.030      0.400      0.689      -0.048       0.072
C(shoot_player)[T.gerald henderson]                 -0.0132      0.031     -0.424      0.672      -0.074       0.048
C(shoot_player)[T.giannis antetokounmpo]            -0.0797      0.030     -2.615      0.009      -0.139      -0.020
C(shoot_player)[T.glen davis]                       -0.1171      0.035     -3.384      0.001      -0.185      -0.049
C(shoot_player)[T.goran dragic]                     -0.0846      0.030     -2.856      0.004      -0.143      -0.027
C(shoot_player)[T.gordon hayward]                   -0.0484      0.030     -1.624      0.104      -0.107       0.010
C(shoot_player)[T.gorgui dieng]                     -0.0919      0.031     -2.957      0.003      -0.153      -0.031
C(shoot_player)[T.greg monroe]                      -0.1247      0.031     -4.057      0.000      -0.185      -0.064
C(shoot_player)[T.greg smith]                       -0.1384      0.058     -2.381      0.017      -0.252      -0.024
C(shoot_player)[T.greivis vasquez]                  -0.0176      0.031     -0.578      0.563      -0.077       0.042
C(shoot_player)[T.harrison barnes]                  -0.0733      0.031     -2.364      0.018      -0.134      -0.013
C(shoot_player)[T.hedo turkoglu]                     0.0525      0.043      1.234      0.217      -0.031       0.136
C(shoot_player)[T.henry sims]                       -0.0545      0.032     -1.717      0.086      -0.117       0.008
C(shoot_player)[T.hollis thompson]                  -0.0363      0.032     -1.120      0.263      -0.100       0.027
C(shoot_player)[T.isaiah thomas]                    -0.0369      0.031     -1.208      0.227      -0.097       0.023
C(shoot_player)[T.jakarr sampson]                   -0.0958      0.036     -2.694      0.007      -0.165      -0.026
C(shoot_player)[T.jamal crawford]                    0.0300      0.030      1.012      0.312      -0.028       0.088
C(shoot_player)[T.james ennis]                      -0.1023      0.038     -2.699      0.007      -0.177      -0.028
C(shoot_player)[T.james harden]                      0.0081      0.030      0.272      0.786      -0.050       0.067
C(shoot_player)[T.james johnson]                    -0.1327      0.033     -3.999      0.000      -0.198      -0.068
C(shoot_player)[T.jared dudley]                     -0.0411      0.031     -1.314      0.189      -0.102       0.020
C(shoot_player)[T.jared sullinger]                  -0.0454      0.031     -1.468      0.142      -0.106       0.015
C(shoot_player)[T.jarrett jack]                     -0.0380      0.030     -1.251      0.211      -0.097       0.022
C(shoot_player)[T.jason maxiell]                    -0.0785      0.038     -2.056      0.040      -0.153      -0.004
C(shoot_player)[T.jason smith]                      -0.0298      0.032     -0.947      0.344      -0.092       0.032
C(shoot_player)[T.jason terry]                       0.0054      0.033      0.165      0.869      -0.058       0.069
C(shoot_player)[T.jason thompson]                   -0.1094      0.033     -3.352      0.001      -0.173      -0.045
C(shoot_player)[T.jeff green]                       -0.0300      0.030     -0.997      0.319      -0.089       0.029
C(shoot_player)[T.jeff teague]                      -0.0839      0.031     -2.734      0.006      -0.144      -0.024
C(shoot_player)[T.jerami grant]                     -0.0632      0.035     -1.796      0.073      -0.132       0.006
C(shoot_player)[T.jeremy lamb]                       0.0009      0.037      0.025      0.980      -0.071       0.073
C(shoot_player)[T.jeremy lin]                       -0.0399      0.031     -1.298      0.194      -0.100       0.020
C(shoot_player)[T.jerome jordan]                    -0.1131      0.047     -2.397      0.017      -0.205      -0.021
C(shoot_player)[T.jerryd bayless]                   -0.0077      0.031     -0.247      0.805      -0.069       0.053
C(shoot_player)[T.jimmer dredette]                  -0.1059      0.037     -2.831      0.005      -0.179      -0.033
C(shoot_player)[T.jimmy butler]                     -0.0482      0.030     -1.603      0.109      -0.107       0.011
C(shoot_player)[T.jj hickson]                       -0.1427      0.032     -4.456      0.000      -0.205      -0.080
C(shoot_player)[T.jj redick]                        -0.0082      0.030     -0.271      0.786      -0.068       0.051
C(shoot_player)[T.joakim noah]                      -0.0981      0.032     -3.068      0.002      -0.161      -0.035
C(shoot_player)[T.joe harris]                       -0.0050      0.044     -0.115      0.909      -0.091       0.081
C(shoot_player)[T.joe johnson]                      -0.0114      0.030     -0.379      0.705      -0.070       0.048
C(shoot_player)[T.joey dorsey]                      -0.1323      0.044     -3.036      0.002      -0.218      -0.047
C(shoot_player)[T.john henson]                      -0.1606      0.035     -4.566      0.000      -0.230      -0.092
C(shoot_player)[T.john wall]                        -0.0282      0.030     -0.935      0.350      -0.087       0.031
C(shoot_player)[T.jon ingles]                       -0.0035      0.034     -0.105      0.916      -0.069       0.062
C(shoot_player)[T.jon leuer]                        -0.1190      0.034     -3.521      0.000      -0.185      -0.053
C(shoot_player)[T.jonas jerebko]                    -0.0502      0.033     -1.501      0.133      -0.116       0.015
C(shoot_player)[T.jonas valanciunas]                -0.1278      0.031     -4.109      0.000      -0.189      -0.067
C(shoot_player)[T.jordan farmar]                     0.0334      0.036      0.915      0.360      -0.038       0.105
C(shoot_player)[T.jordan hill]                      -0.0587      0.031     -1.882      0.060      -0.120       0.002
C(shoot_player)[T.jose calderon]                     0.0291      0.033      0.882      0.378      -0.036       0.094
C(shoot_player)[T.jose juan barea]                  -0.0329      0.030     -1.083      0.279      -0.093       0.027
C(shoot_player)[T.jrue holiday]                     -0.0335      0.033     -1.021      0.307      -0.098       0.031
C(shoot_player)[T.jusuf nurkic]                     -0.1361      0.033     -4.071      0.000      -0.202      -0.071
C(shoot_player)[T.kawhi leonard]                    -0.0398      0.033     -1.189      0.235      -0.105       0.026
C(shoot_player)[T.kelly olynyk]                     -0.1217      0.034     -3.578      0.000      -0.188      -0.055
C(shoot_player)[T.kemba walker]                     -0.0299      0.032     -0.924      0.355      -0.093       0.033
C(shoot_player)[T.kendrick perkins]                 -0.1856      0.034     -5.415      0.000      -0.253      -0.118
C(shoot_player)[T.kenneth faried]                   -0.1122      0.031     -3.636      0.000      -0.173      -0.052
C(shoot_player)[T.kent bazemore]                    -0.0475      0.036     -1.335      0.182      -0.117       0.022
C(shoot_player)[T.kentavious caldwell-pope]         -0.0161      0.030     -0.531      0.595      -0.076       0.043
C(shoot_player)[T.kevin garnett]                    -0.0699      0.033     -2.128      0.033      -0.134      -0.006
C(shoot_player)[T.kevin love]                       -0.0344      0.030     -1.146      0.252      -0.093       0.024

In [90]:
import statsmodels.formula.api as smf

players_to_run = [
    "russell westbrook",
    "james harden",
    "andrew wiggins",
    "stephen curry"
]

reg3_results = {}

for p in players_to_run:
    df_p = Shotlog_1415[Shotlog_1415['shoot_player'] == p].copy()

    # Skip if too little data
    if df_p.shape[0] < 30:
        print(f"{p}: Not enough data ({df_p.shape[0]} shots)")
        continue

    # Drop constant columns (no variation → regression kill switch)
    for col in ['points','quarter','home_away']:
        if df_p[col].nunique() < 2:
            df_p.drop(columns=[col], inplace=True)

    formula = 'error ~ lag_error + shot_dist + dribbles + touch_time + closest_def_dist'

    # Add categorical predictors only if variation exists
    if 'points' in df_p.columns:
        formula += ' + C(points)'
    if 'quarter' in df_p.columns:
        formula += ' + C(quarter)'
    if 'home_away' in df_p.columns:
        formula += ' + home_away'

    print(f"\n\n===== {p} =====")
    model = smf.ols(formula=formula, data=df_p).fit()
    reg3_results[p] = model
    print(model.summary())

===== russell westbrook =====
                            OLS Regression Results
==============================================================================
Dep. Variable:                  error   R-squared:                       0.065
Model:                            OLS   Adj. R-squared:                  0.054
Method:                 Least Squares   F-statistic:                     5.753
Date:                Wed, 03 Dec 2025   Prob (F-statistic):           4.91e-09
Time:                        23:33:50   Log-Likelihood:                -632.90
No. Observations:                 923   AIC:                             1290.
Df Residuals:                     911   BIC:                             1348.
Df Model:                          11
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept            0.1162      0.051      2.293      0.022       0.017       0.216
C(points)[T.3]      -0.0455      0.060     -0.762      0.446      -0.163       0.072
C(quarter)[T.2]     -0.0418      0.046     -0.913      0.361      -0.132       0.048
C(quarter)[T.3]     -0.0446      0.043     -1.034      0.301      -0.129       0.040
C(quarter)[T.4]     -0.0257      0.047     -0.542      0.588      -0.119       0.067
C(quarter)[T.5]      0.0885      0.113      0.781      0.435      -0.134       0.311
home_away[T.H]       0.0436      0.032      1.344      0.179      -0.020       0.107
lag_error           -0.0107      0.033     -0.326      0.745      -0.075       0.054
shot_dist           -0.0138      0.003     -4.992      0.000      -0.019      -0.008
dribbles            -0.0078      0.011     -0.731      0.465      -0.029       0.013
touch_time           0.0072      0.013      0.572      0.567      -0.018       0.032
closest_def_dist     0.0235      0.006      3.864      0.000       0.012       0.035
==============================================================================
Omnibus:                     4317.475   Durbin-Watson:                   2.028
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              123.758
Skew:                           0.220   Prob(JB):                     1.34e-27
Kurtosis:                       1.261   Cond. No.                         123.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


===== james harden =====
                            OLS Regression Results
==============================================================================
Dep. Variable:                  error   R-squared:                       0.050
Model:                            OLS   Adj. R-squared:                  0.040
Method:                 Least Squares   F-statistic:                     4.750
Date:                Wed, 03 Dec 2025   Prob (F-statistic):           3.89e-07
Time:                        23:33:50   Log-Likelihood:                -691.03
No. Observations:                 995   AIC:                             1406.
Df Residuals:                     983   BIC:                             1465.
Df Model:                          11
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept            0.0808      0.053      1.532      0.126      -0.023       0.184
C(points)[T.3]       0.0583      0.061      0.959      0.338      -0.061       0.178
C(quarter)[T.2]      0.0288      0.045      0.632      0.527      -0.060       0.118
C(quarter)[T.3]      0.0016      0.042      0.037      0.970      -0.081       0.084
C(quarter)[T.4]      0.0324      0.048      0.682      0.496      -0.061       0.126
C(quarter)[T.5]      0.1987      0.159      1.247      0.213      -0.114       0.512
home_away[T.H]       0.0005      0.032      0.016      0.987      -0.062       0.063
lag_error            0.0362      0.031      1.155      0.248      -0.025       0.098
shot_dist           -0.0144      0.003     -4.436      0.000      -0.021      -0.008
dribbles             0.0115      0.008      1.373      0.170      -0.005       0.028
touch_time          -0.0148      0.010     -1.510      0.131      -0.034       0.004
closest_def_dist     0.0325      0.009      3.813      0.000       0.016       0.049
==============================================================================
Omnibus:                     4461.129   Durbin-Watson:                   2.045
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              137.571
Skew:                           0.212   Prob(JB):                     1.34e-30
Kurtosis:                       1.228   Cond. No.                         200.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


===== andrew wiggins =====
                            OLS Regression Results
==============================================================================
Dep. Variable:                  error   R-squared:                       0.084
Model:                            OLS   Adj. R-squared:                  0.070
Method:                 Least Squares   F-statistic:                     6.019
Date:                Wed, 03 Dec 2025   Prob (F-statistic):           1.85e-09
Time:                        23:33:50   Log-Likelihood:                -499.07
No. Observations:                 738   AIC:                             1022.
Df Residuals:                     726   BIC:                             1077.
Df Model:                          11
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept            0.2044      0.056      3.669      0.000       0.095       0.314
C(points)[T.3]       0.0903      0.070      1.294      0.196      -0.047       0.227
C(quarter)[T.2]     -0.0019      0.051     -0.038      0.970      -0.103       0.099
C(quarter)[T.3]     -0.0053      0.048     -0.111      0.912      -0.099       0.089
C(quarter)[T.4]      0.0226      0.051      0.440      0.660      -0.078       0.123
C(quarter)[T.5]     -0.1873      0.281     -0.667      0.505      -0.738       0.364
home_away[T.H]       0.0270      0.036      0.749      0.454      -0.044       0.098
lag_error            0.0139      0.036      0.385      0.700      -0.057       0.085
shot_dist           -0.0226      0.003     -7.171      0.000      -0.029      -0.016
dribbles            -0.0158      0.018     -0.898      0.369      -0.050       0.019
touch_time          -0.0055      0.018     -0.316      0.752      -0.040       0.029
closest_def_dist     0.0234      0.009      2.748      0.006       0.007       0.040
==============================================================================
Omnibus:                     4186.738   Durbin-Watson:                   1.961
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               87.383
Skew:                           0.229   Prob(JB):                     1.06e-19
Kurtosis:                       1.378   Cond. No.                         238.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


===== stephen curry =====
                            OLS Regression Results
==============================================================================
Dep. Variable:                  error   R-squared:                       0.070
Model:                            OLS   Adj. R-squared:                  0.059
Method:                 Least Squares   F-statistic:                     6.147
Date:                Wed, 03 Dec 2025   Prob (F-statistic):           8.60e-10
Time:                        23:33:50   Log-Likelihood:                -626.94
No. Observations:                 910   AIC:                             1278.
Df Residuals:                     898   BIC:                             1336.
Df Model:                          11
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept            0.2137      0.056      3.822      0.000       0.104       0.323
C(points)[T.3]       0.1124      0.056      2.008      0.045       0.003       0.222
C(quarter)[T.2]     -0.0362      0.047     -0.763      0.446      -0.129       0.057
C(quarter)[T.3]     -0.0331      0.042     -0.790      0.430      -0.115       0.049
C(quarter)[T.4]     -0.0640      0.047     -1.356      0.175      -0.157       0.029
C(quarter)[T.5]      0.1022      0.203      0.504      0.614      -0.295       0.500
home_away[T.H]       0.0170      0.033      0.521      0.603      -0.047       0.081
lag_error           -0.0288      0.033     -0.884      0.377      -0.093       0.035
shot_dist           -0.0186      0.003     -6.258      0.000      -0.024      -0.013
dribbles             0.0140      0.013      1.082      0.279      -0.011       0.039
touch_time          -0.0194      0.016     -1.219      0.223      -0.051       0.012
closest_def_dist     0.0223      0.006      3.473      0.001       0.010       0.035
==============================================================================
Omnibus:                     4280.211   Durbin-Watson:                   2.101
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              114.762
Skew:                           0.068   Prob(JB):                     1.20e-25
Kurtosis:                       1.266   Cond. No.                         262.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [91]:
import statsmodels.formula.api as smf

players_to_run = [
    "cole aldrich",
    "reggie jackson",
    "stephen curry",
    "alonzo gee"
]

reg3_results = {}

for p in players_to_run:
    df_p = Shotlog_1415[Shotlog_1415['shoot_player'] == p].copy()

    # Skip if too little data
    if df_p.shape[0] < 30:
        print(f"{p}: Not enough data ({df_p.shape[0]} shots)")
        continue

    # Drop constant columns (no variation → regression kill switch)
    for col in ['points','quarter','home_away']:
        if df_p[col].nunique() < 2:
            df_p.drop(columns=[col], inplace=True)

    formula = 'error ~ lag_error + shot_dist + dribbles + touch_time + closest_def_dist'

    # Add categorical predictors only if variation exists
    if 'points' in df_p.columns:
        formula += ' + C(points)'
    if 'quarter' in df_p.columns:
        formula += ' + C(quarter)'
    if 'home_away' in df_p.columns:
        formula += ' + home_away'

    print(f"\n\n===== {p} =====")
    model = smf.ols(formula=formula, data=df_p).fit()
    reg3_results[p] = model
    print(model.summary())

===== cole aldrich =====
                            OLS Regression Results
==============================================================================
Dep. Variable:                  error   R-squared:                       0.121
Model:                            OLS   Adj. R-squared:                  0.065
Method:                 Least Squares   F-statistic:                     2.181
Date:                Wed, 03 Dec 2025   Prob (F-statistic):             0.0266
Time:                        23:36:50   Log-Likelihood:                -101.04
No. Observations:                 153   AIC:                             222.1
Df Residuals:                     143   BIC:                             252.4
Df Model:                           9
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept            0.0180      0.165      0.109      0.914      -0.309       0.345
C(quarter)[T.2]      0.0081      0.123      0.066      0.947      -0.235       0.251
C(quarter)[T.3]      0.1061      0.118      0.898      0.371      -0.127       0.340
C(quarter)[T.4]      0.0439      0.127      0.347      0.729      -0.206       0.294
home_away[T.H]      -0.1098      0.081     -1.358      0.176      -0.270       0.050
lag_error            0.0049      0.080      0.061      0.951      -0.153       0.163
shot_dist           -0.0356      0.016     -2.252      0.026      -0.067      -0.004
dribbles             0.0588      0.076      0.772      0.441      -0.092       0.209
touch_time          -0.0417      0.034     -1.239      0.217      -0.108       0.025
closest_def_dist     0.0917      0.032      2.834      0.005       0.028       0.156
==============================================================================
Omnibus:                      554.161   Durbin-Watson:                   1.909
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               13.892
Skew:                           0.077   Prob(JB):                     0.000963
Kurtosis:                       1.532   Cond. No.                         41.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


===== reggie jackson =====
                            OLS Regression Results
==============================================================================
Dep. Variable:                  error   R-squared:                       0.074
Model:                            OLS   Adj. R-squared:                  0.055
Method:                 Least Squares   F-statistic:                     3.916
Date:                Wed, 03 Dec 2025   Prob (F-statistic):           8.15e-06
Time:                        23:36:50   Log-Likelihood:                -406.88
No. Observations:                 604   AIC:                             839.8
Df Residuals:                     591   BIC:                             897.0
Df Model:                          12
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept            0.2383      0.079      3.008      0.003       0.083       0.394
C(points)[T.3]       0.0051      0.068      0.075      0.940      -0.129       0.139
C(quarter)[T.2]     -0.0226      0.064     -0.354      0.724      -0.148       0.103
C(quarter)[T.3]     -0.0159      0.067     -0.236      0.814      -0.148       0.116
C(quarter)[T.4]     -0.0134      0.064     -0.208      0.835      -0.139       0.113
C(quarter)[T.5]     -0.1887      0.163     -1.161      0.246      -0.508       0.131
C(quarter)[T.6]     -0.5188      0.484     -1.072      0.284      -1.470       0.432
home_away[T.H]      -0.0111      0.040     -0.277      0.782      -0.090       0.068
lag_error            0.0309      0.040      0.779      0.436      -0.047       0.109
shot_dist           -0.0172      0.004     -4.682      0.000      -0.024      -0.010
dribbles             0.0053      0.014      0.375      0.707      -0.022       0.033
touch_time          -0.0129      0.017     -0.749      0.454      -0.047       0.021
closest_def_dist     0.0177      0.010      1.712      0.087      -0.003       0.038
==============================================================================
Omnibus:                     3621.507   Durbin-Watson:                   1.891
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               74.695
Skew:                           0.301   Prob(JB):                     6.03e-17
Kurtosis:                       1.386   Cond. No.                         462.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


===== stephen curry =====
                            OLS Regression Results
==============================================================================
Dep. Variable:                  error   R-squared:                       0.070
Model:                            OLS   Adj. R-squared:                  0.059
Method:                 Least Squares   F-statistic:                     6.147
Date:                Wed, 03 Dec 2025   Prob (F-statistic):           8.60e-10
Time:                        23:36:50   Log-Likelihood:                -626.94
No. Observations:                 910   AIC:                             1278.
Df Residuals:                     898   BIC:                             1336.
Df Model:                          11
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept            0.2137      0.056      3.822      0.000       0.104       0.323
C(points)[T.3]       0.1124      0.056      2.008      0.045       0.003       0.222
C(quarter)[T.2]     -0.0362      0.047     -0.763      0.446      -0.129       0.057
C(quarter)[T.3]     -0.0331      0.042     -0.790      0.430      -0.115       0.049
C(quarter)[T.4]     -0.0640      0.047     -1.356      0.175      -0.157       0.029
C(quarter)[T.5]      0.1022      0.203      0.504      0.614      -0.295       0.500
home_away[T.H]       0.0170      0.033      0.521      0.603      -0.047       0.081
lag_error           -0.0288      0.033     -0.884      0.377      -0.093       0.035
shot_dist           -0.0186      0.003     -6.258      0.000      -0.024      -0.013
dribbles             0.0140      0.013      1.082      0.279      -0.011       0.039
touch_time          -0.0194      0.016     -1.219      0.223      -0.051       0.012
closest_def_dist     0.0223      0.006      3.473      0.001       0.010       0.035
==============================================================================
Omnibus:                     4280.211   Durbin-Watson:                   2.101
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              114.762
Skew:                           0.068   Prob(JB):                     1.20e-25
Kurtosis:                       1.266   Cond. No.                         262.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


===== alonzo gee =====
                            OLS Regression Results
==============================================================================
Dep. Variable:                  error   R-squared:                       0.222
Model:                            OLS   Adj. R-squared:                  0.127
Method:                 Least Squares   F-statistic:                     2.332
Date:                Wed, 03 Dec 2025   Prob (F-statistic):             0.0142
Time:                        23:36:50   Log-Likelihood:                -60.927
No. Observations:                 102   AIC:                             145.9
Df Residuals:                      90   BIC:                             177.4
Df Model:                          11
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept           -0.0172      0.525     -0.033      0.974      -1.060       1.026
C(points)[T.3]       0.2184      0.257      0.851      0.397      -0.291       0.728
C(quarter)[T.2]      0.1718      0.508      0.338      0.736      -0.838       1.182
C(quarter)[T.3]      0.4130      0.505      0.817      0.416      -0.591       1.417
C(quarter)[T.4]      0.2757      0.497      0.554      0.581      -0.712       1.263
C(quarter)[T.5]      0.6438      0.694      0.928      0.356      -0.734       2.022
home_away[T.H]      -0.0108      0.096     -0.113      0.910      -0.201       0.179
lag_error           -0.2767      0.096     -2.874      0.005      -0.468      -0.085
shot_dist           -0.0328      0.012     -2.632      0.010      -0.058      -0.008
dribbles            -0.0648      0.061     -1.057      0.293      -0.187       0.057
touch_time           0.0135      0.056      0.239      0.812      -0.099       0.125
closest_def_dist     0.0236      0.015      1.569      0.120      -0.006       0.053
==============================================================================
Omnibus:                       33.365   Durbin-Watson:                   1.931
Prob(Omnibus):                  0.000   Jarque-Bera (JB):                6.539
Skew:                          -0.178   Prob(JB):                       0.0380
Kurtosis:                       1.812   Cond. No.                         323.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.